// ── AUTO-GENERATED from suppliers.xlsx ──────────────────────────────────────
// Do not edit by hand. Re-run parse_excel.py to regenerate.

export type ExcelSupplier = { norm: string; display: string; totalAmount: number; rows: number };
export type ExcelItem = { norm: string; display: string; type: "RM" | "PACK" | "OTHERS"; uom: string; avgPrice: number | null; category: string };
export type ExcelSupItem = { supplier: string; item: string; uom: string; avgPrice: number | null; lastPrice: number | null; count: number };

export const EXCEL_SUPPLIERS: ExcelSupplier[] = [
  { norm: "AL AJMERA", display: "Al Ajmera", totalAmount: 14170.0, rows: 48 },
  { norm: "AL FONDOKIA", display: "AL FONDOKIA", totalAmount: 1920.0, rows: 3 },
  { norm: "AL SAFA", display: "Al SAFA", totalAmount: 637.0, rows: 3 },
  { norm: "AL WAJBA", display: "AL WAJBA", totalAmount: 15642.0, rows: 27 },
  { norm: "AMOUDI", display: "AMOUDI", totalAmount: 107430.6, rows: 375 },
  { norm: "BRADMA", display: "BRADMA", totalAmount: 8940.0, rows: 15 },
  { norm: "CASH", display: "CASH", totalAmount: 8705.25, rows: 26 },
  { norm: "CASH/AL HADIDY", display: "CASH/AL HADIDY", totalAmount: 35.0, rows: 1 },
  { norm: "CASH/DELTA", display: "Cash/delta", totalAmount: 1120.0, rows: 4 },
  { norm: "CASH/ROBBY", display: "CASH/ROBBY", totalAmount: 360.0, rows: 2 },
  { norm: "CHEF", display: "CHEF", totalAmount: 75.0, rows: 1 },
  { norm: "DELTA", display: "DELTA", totalAmount: 250.0, rows: 1 },
  { norm: "ETIHAD", display: "ETIHAD", totalAmount: 149400.0, rows: 342 },
  { norm: "FIRDOUS", display: "FIRDOUS", totalAmount: 316.0, rows: 1 },
  { norm: "FORWARD GROUP", display: "Forward Group", totalAmount: 3750.0, rows: 2 },
  { norm: "GULF STREAM", display: "GULF STREAM", totalAmount: 29150.0, rows: 56 },
  { norm: "HOLLANDI", display: "HOLLANDI", totalAmount: 132266.0, rows: 297 },
  { norm: "HOTPACK", display: "HOTPACK", totalAmount: 330.0, rows: 1 },
  { norm: "JANA INT. TRD.", display: "JANA Int. Trd.", totalAmount: 525.0, rows: 4 },
  { norm: "JEWAN", display: "JEWAN", totalAmount: 288.0, rows: 1 },
  { norm: "JEWAN FOOD", display: "JEWAN FOOD", totalAmount: 36.0, rows: 1 },
  { norm: "MAAS", display: "MAAS", totalAmount: 256568.25, rows: 621 },
  { norm: "PERFACT MEDIA", display: "PERFACT MEDIA", totalAmount: 190.0, rows: 1 },
  { norm: "PRINT CARE", display: "PRINT CARE", totalAmount: 8300.0, rows: 10 },
  { norm: "PROGRESSIVE", display: "PROGRESSIVE", totalAmount: 1672.0, rows: 2 },
  { norm: "PROVENDER", display: "ProVender", totalAmount: 590.0, rows: 2 },
  { norm: "QFM", display: "QFM", totalAmount: 893192.0, rows: 128 },
  { norm: "QNITED", display: "QNITED", totalAmount: 30719.0, rows: 22 },
  { norm: "QRT", display: "QRT", totalAmount: 135.0, rows: 1 },
  { norm: "RAMELIE", display: "RAMELIE", totalAmount: 4825.0, rows: 7 },
  { norm: "RAWABI", display: "RAWABI", totalAmount: 39651.0, rows: 92 },
  { norm: "REALPACK", display: "REALPACK", totalAmount: 1568.0, rows: 3 },
  { norm: "ROYAL PACK", display: "ROYAL PACK", totalAmount: 1160.0, rows: 4 },
  { norm: "SANA FOOD", display: "SANA FOOD", totalAmount: 2530.0, rows: 14 },
  { norm: "SEA SHORE", display: "SEA SHORE", totalAmount: 0.0, rows: 1 },
  { norm: "VALENCIA", display: "VALENCIA", totalAmount: 103398.6, rows: 312 },
  { norm: "VERSA", display: "VERSA", totalAmount: 704.0, rows: 2 },
  { norm: "WEST BAY", display: "WEST BAY", totalAmount: 8937.5, rows: 27 },
];

export const EXCEL_ITEMS: ExcelItem[] = [
  { norm: "1000395", display: "1000395", type: "PACK", uom: "KG", avgPrice: 11.5, category: "packaging_disposables" },
  { norm: "ANGLE BAKING POWDER(10KG)", display: "ANGLE BAKING POWDER(10KG)", type: "RM", uom: "BAG", avgPrice: 78.0, category: "leavening_improvers" },
  { norm: "APPLE -(SUPPLY TO SCHOOL)", display: "APPLE -(SUPPLY TO SCHOOL)", type: "RM", uom: "CRT", avgPrice: 118.0, category: "other_rm" },
  { norm: "APPLE FILLING(2.7KG)", display: "APPLE FILLING(2.7KG)", type: "RM", uom: "KG", avgPrice: 43.9937, category: "flavors_fillings" },
  { norm: "AREEJ MARGARINE(25KG)", display: "AREEJ MARGARINE(25KG)", type: "RM", uom: "BAG", avgPrice: 161.5319, category: "fats_oils" },
  { norm: "AREEJ MARGARINE(25KG)- UNSALTED", display: "AREEJ MARGARINE(25KG)- UNSALTED", type: "RM", uom: "BAG", avgPrice: 200.0, category: "fats_oils" },
  { norm: "AREEJ MARGARINE/FERN BLENDED BUTTER(25KG)", display: "AREEJ MARGARINE/FERN BLENDED BUTTER(25KG)", type: "RM", uom: "KG", avgPrice: 7.96, category: "fats_oils" },
  { norm: "BACKING BUTTER PAPER PLAIN 2*500", display: "BACKING BUTTER PAPER PLAIN 2*500", type: "RM", uom: "PCS", avgPrice: 0.05, category: "fats_oils" },
  { norm: "BAKELS BACOM A100 20KG", display: "BAKELS BACOM A100 20KG", type: "RM", uom: "KG", avgPrice: 12.0, category: "leavening_improvers" },
  { norm: "BAKERS KNIFE 65CM", display: "BAKERS KNIFE 65CM", type: "OTHERS", uom: "PCS", avgPrice: 151.0, category: "cleaning_supplies" },
  { norm: "BAKING BUTTER PAPER(1X500 PCS)", display: "BAKING BUTTER PAPER(1X500 PCS)", type: "RM", uom: "PCS", avgPrice: 0.24, category: "fats_oils" },
  { norm: "BAKING PAPER(1X500 PCS)", display: "BAKING PAPER(1X500 PCS)", type: "PACK", uom: "CRT", avgPrice: 39.889, category: "packaging_disposables" },
  { norm: "BAKING POWDER(10KG)", display: "BAKING POWDER(10KG)", type: "RM", uom: "KG", avgPrice: 39.0222, category: "leavening_improvers" },
  { norm: "BAKING POWDER(1KG)", display: "BAKING POWDER(1KG)", type: "RM", uom: "PCS", avgPrice: 17.0, category: "leavening_improvers" },
  { norm: "BAKING POWDER(25KG)", display: "BAKING POWDER(25KG)", type: "RM", uom: "BAG", avgPrice: 78.0, category: "leavening_improvers" },
  { norm: "BISCUITES -(SUPPLY TO SCHOOL)", display: "BISCUITES -(SUPPLY TO SCHOOL)", type: "OTHERS", uom: "PACK", avgPrice: 9.5, category: "cleaning_supplies" },
  { norm: "BLACK SEEDS", display: "BLACK SEEDS", type: "RM", uom: "KG", avgPrice: 16.0, category: "flavors_fillings" },
  { norm: "BLEACH LIQUID 6X3.78 LTR CLOROX", display: "BLEACH LIQUID 6X3.78 LTR CLOROX", type: "OTHERS", uom: "CRT", avgPrice: 88.0, category: "cleaning_supplies" },
  { norm: "BLEACH LIQUID 6X3.78LTR CLOROX", display: "BLEACH LIQUID 6X3.78LTR CLOROX", type: "OTHERS", uom: "CRT", avgPrice: 88.0, category: "cleaning_supplies" },
  { norm: "BLUE HAND SLEEVE 20*100PCS", display: "BLUE HAND SLEEVE 20*100PCS", type: "PACK", uom: "CRT", avgPrice: 85.0, category: "ppe_hygiene" },
  { norm: "BLUE NONWOVEN MOB CAP 10*100PCS", display: "BLUE NONWOVEN MOB CAP 10*100PCS", type: "PACK", uom: "CRT", avgPrice: 30.0, category: "ppe_hygiene" },
  { norm: "BOTTLE AND CAN OPNER", display: "BOTTLE AND CAN OPNER", type: "OTHERS", uom: "PCS", avgPrice: 54.0, category: "cleaning_supplies" },
  { norm: "BREAD IMPROVER(10KG)", display: "BREAD IMPROVER(10KG)", type: "RM", uom: "BAG", avgPrice: 151.5909, category: "leavening_improvers" },
  { norm: "BREAD IMPROVER(15KG)", display: "BREAD IMPROVER(15KG)", type: "RM", uom: "BAG", avgPrice: 161.9529, category: "leavening_improvers" },
  { norm: "BREAD WIRE 10KG PACK", display: "BREAD WIRE 10KG PACK", type: "PACK", uom: "CRT", avgPrice: 224.0, category: "purchased_goods" },
  { norm: "BROWN BREAD", display: "BROWN BREAD", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "BROWN BREAD 25X40", display: "BROWN BREAD 25X40", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "BURGER BUN 4 PCS", display: "BURGER BUN 4 PCS", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "BURGER BUN 4 PCS(10X12)", display: "BURGER BUN 4 PCS(10X12)", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "BUTTER BLOCK(25KG)- UNSALTED", display: "BUTTER BLOCK(25KG)- UNSALTED", type: "RM", uom: "BAG", avgPrice: 200.0, category: "fats_oils" },
  { norm: "BUTTER ROLL 12X9INCH", display: "BUTTER ROLL 12X9INCH", type: "RM", uom: "KG", avgPrice: 13.0, category: "fats_oils" },
  { norm: "BUTTER ROLL 300 G", display: "BUTTER ROLL 300 G", type: "RM", uom: "KG", avgPrice: 13.0, category: "fats_oils" },
  { norm: "CAKE GEL(1 PACK X 5KG)", display: "CAKE GEL(1 PACK X 5KG)", type: "RM", uom: "CRT", avgPrice: 51.1579, category: "leavening_improvers" },
  { norm: "CALCIUM PROPIONATE(20KG)", display: "CALCIUM PROPIONATE(20KG)", type: "RM", uom: "BAG", avgPrice: 232.0161, category: "leavening_improvers" },
  { norm: "CHAKKI ATTA FLOUR(50KG)", display: "CHAKKI ATTA FLOUR(50KG)", type: "RM", uom: "KG", avgPrice: 24.408, category: "flour" },
  { norm: "CHAPATHI PLASTIC", display: "CHAPATHI PLASTIC", type: "PACK", uom: "KG", avgPrice: 13.0, category: "packaging_disposables" },
  { norm: "CHAPATI - RADISSON BLUE HOTEL", display: "CHAPATI - RADISSON BLUE HOTEL", type: "RM", uom: "PKT", avgPrice: 1.1786, category: "other_rm" },
  { norm: "CHINA PAPER STICKER 6CM*6CM 2", display: "CHINA PAPER STICKER 6CM*6CM 2", type: "PACK", uom: "PCS", avgPrice: 0.093, category: "packaging_disposables" },
  { norm: "CHOCKLATE FILLING(5KG)", display: "CHOCKLATE FILLING(5KG)", type: "RM", uom: "KG", avgPrice: 42.2667, category: "flavors_fillings" },
  { norm: "CHOCKLATE FILLING(5KG)8%", display: "CHOCKLATE FILLING(5KG)8%", type: "RM", uom: "KG", avgPrice: 44.0, category: "flavors_fillings" },
  { norm: "CHOCOLATE -(SUPPLY TO SCHOOL)", display: "CHOCOLATE -(SUPPLY TO SCHOOL)", type: "OTHERS", uom: "PACK", avgPrice: 71.25, category: "cleaning_supplies" },
  { norm: "CINNAMON POWDER(1KG)", display: "CINNAMON POWDER(1KG)", type: "RM", uom: "KG", avgPrice: 20.0, category: "flavors_fillings" },
  { norm: "CINNAMON POWDER(5KG)", display: "CINNAMON POWDER(5KG)", type: "RM", uom: "KG", avgPrice: 21.0, category: "flavors_fillings" },
  { norm: "CLING FILM 1X45CM 5KG(JMBO)", display: "CLING FILM 1X45CM 5KG(JMBO)", type: "RM", uom: "KG", avgPrice: 23.5556, category: "other_rm" },
  { norm: "COOKIES MIX -(SUPPLY TO SCHOOL)", display: "COOKIES MIX -(SUPPLY TO SCHOOL)", type: "OTHERS", uom: "PCS", avgPrice: 1.1, category: "cleaning_supplies" },
  { norm: "COOKIES, BISCUITS & CHOCOLATES(SUPPLY TO SCHOOL EVENTS)", display: "COOKIES, BISCUITS & CHOCOLATES(SUPPLY TO SCHOOL EVENTS)", type: "OTHERS", uom: "", avgPrice: null, category: "cleaning_supplies" },
  { norm: "COTTON GLOVES 10PC/PKT", display: "COTTON GLOVES 10PC/PKT", type: "OTHERS", uom: "CRT", avgPrice: 280.0, category: "cleaning_supplies" },
  { norm: "COTTON GLOVES 600 PAIR", display: "COTTON GLOVES 600 PAIR", type: "OTHERS", uom: "CRT", avgPrice: 317.0808, category: "cleaning_supplies" },
  { norm: "CREAM BUN PLASTIC 10KG/ROLL", display: "CREAM BUN PLASTIC 10KG/ROLL", type: "PACK", uom: "KG", avgPrice: 16.0, category: "purchased_goods" },
  { norm: "CREAM CHEESE(1KG)", display: "CREAM CHEESE(1KG)", type: "RM", uom: "KG", avgPrice: 21.7419, category: "fats_oils" },
  { norm: "CROISSANT BUTTER(10KG)", display: "CROISSANT BUTTER(10KG)", type: "RM", uom: "KG", avgPrice: 65.9722, category: "fats_oils" },
  { norm: "CUP CAKE 65 G 10KG/ROLL", display: "CUP CAKE 65 G 10KG/ROLL", type: "PACK", uom: "KG", avgPrice: 16.0, category: "purchased_goods" },
  { norm: "CUP CAKE PAPER(1000 PCS)", display: "CUP CAKE PAPER(1000 PCS)", type: "PACK", uom: "PCS", avgPrice: 0.0095, category: "packaging_disposables" },
  { norm: "CUP CAKE PAPER(1000 PCS)9CM", display: "CUP CAKE PAPER(1000 PCS)9CM", type: "PACK", uom: "PKT", avgPrice: 9.51, category: "packaging_disposables" },
  { norm: "CUP CAKE PAPER(12X1000PCS)9.5CM", display: "CUP CAKE PAPER(12X1000PCS)9.5CM", type: "PACK", uom: "CRT", avgPrice: 145.0, category: "packaging_disposables" },
  { norm: "CUP CAKE PAPER(16X1000PCS)9.5CM", display: "CUP CAKE PAPER(16X1000PCS)9.5CM", type: "RM", uom: "CRT", avgPrice: 179.0, category: "other_rm" },
  { norm: "CUP CAKE PAPER(25X1000 PCS)", display: "CUP CAKE PAPER(25X1000 PCS)", type: "PACK", uom: "PCS", avgPrice: 0.0084, category: "packaging_disposables" },
  { norm: "DATES PASTE(1KG*12)", display: "DATES PASTE(1KG*12)", type: "RM", uom: "CRT", avgPrice: 108.0, category: "flavors_fillings" },
  { norm: "DATES PASTE(5KG*3)", display: "DATES PASTE(5KG*3)", type: "RM", uom: "CRT", avgPrice: 72.614, category: "flavors_fillings" },
  { norm: "DINNER ROLL", display: "DINNER ROLL", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "DRY YEAST(500G X 20)", display: "DRY YEAST(500G X 20)", type: "RM", uom: "CRT", avgPrice: 72.0212, category: "leavening_improvers" },
  { norm: "ENGLISH CAKE TRAY/PAN CAKE 1000PCS", display: "ENGLISH CAKE TRAY/PAN CAKE 1000PCS", type: "PACK", uom: "PCS", avgPrice: 0.56, category: "packaging_disposables" },
  { norm: "ENGLISH CAKE TRAY/PAN CAKE 800PCS", display: "ENGLISH CAKE TRAY/PAN CAKE 800PCS", type: "PACK", uom: "PCS", avgPrice: 0.56, category: "packaging_disposables" },
  { norm: "ENGLSIH CAKE STICKER- ADJUSTED", display: "ENGLSIH CAKE STICKER- ADJUSTED", type: "PACK", uom: "PCS", avgPrice: 0.3, category: "packaging_disposables" },
  { norm: "FACE MASK 1X50PCS", display: "FACE MASK 1X50PCS", type: "OTHERS", uom: "BOX", avgPrice: 2.713, category: "cleaning_supplies" },
  { norm: "FINE BRAN FLOUR(10KG)", display: "FINE BRAN FLOUR(10KG)", type: "RM", uom: "BAG", avgPrice: 22.0, category: "flour" },
  { norm: "FLOUR NO.1(50KG)", display: "FLOUR NO.1(50KG)", type: "RM", uom: "KG", avgPrice: 61.5451, category: "flour" },
  { norm: "FLOUR NO.1(50KG)(JAMILA)", display: "FLOUR NO.1(50KG)(JAMILA)", type: "RM", uom: "KG", avgPrice: 22.68, category: "flour" },
  { norm: "FLOUR NO.1(50KG)(TURKEY)", display: "FLOUR NO.1(50KG)(TURKEY)", type: "RM", uom: "KG", avgPrice: 2.1, category: "flour" },
  { norm: "FLOUR(MULTICEREAL)(25KG)", display: "FLOUR(MULTICEREAL)(25KG)", type: "RM", uom: "BAG", avgPrice: 450.0, category: "flour" },
  { norm: "FOOD FLAVOR - BANANA 1LTR", display: "FOOD FLAVOR - BANANA 1LTR", type: "RM", uom: "PCS", avgPrice: 58.0, category: "flavors_fillings" },
  { norm: "FOOD FLAVOR - ORANGE 1LTR", display: "FOOD FLAVOR - ORANGE 1LTR", type: "RM", uom: "LTR", avgPrice: 53.5, category: "flavors_fillings" },
  { norm: "FRESH EGG(1CTN X 360)", display: "FRESH EGG(1CTN X 360)", type: "RM", uom: "CRT", avgPrice: 101.9668, category: "dairy_eggs" },
  { norm: "GARBAGE BAG 124*140 10S", display: "GARBAGE BAG 124*140 10S", type: "OTHERS", uom: "CRT", avgPrice: 43.2308, category: "cleaning_supplies" },
  { norm: "GARBAGE BAG 95*110 20PKT", display: "GARBAGE BAG 95*110 20PKT", type: "OTHERS", uom: "CRT", avgPrice: 44.6667, category: "cleaning_supplies" },
  { norm: "GHEE(14L)", display: "GHEE(14L)", type: "RM", uom: "TIN", avgPrice: 96.0, category: "fats_oils" },
  { norm: "GHEE(15L)", display: "GHEE(15L)", type: "RM", uom: "TIN", avgPrice: 52.192, category: "fats_oils" },
  { norm: "GLUTEN(25KG)", display: "GLUTEN(25KG)", type: "RM", uom: "BAG", avgPrice: 147.8466, category: "flour" },
  { norm: "HAIR NET 10*100 PCS", display: "HAIR NET 10*100 PCS", type: "OTHERS", uom: "CRT", avgPrice: 16.5165, category: "cleaning_supplies" },
  { norm: "HAND GLOVES BABY(10PAIR/PKT)", display: "HAND GLOVES BABY(10PAIR/PKT)", type: "PACK", uom: "PKT", avgPrice: 7.0, category: "ppe_hygiene" },
  { norm: "HAND GLOVES MEDICAL(VINYL)", display: "HAND GLOVES MEDICAL(VINYL)", type: "OTHERS", uom: "PKT", avgPrice: 6.5, category: "cleaning_supplies" },
  { norm: "HAND GLOVES RUBBER 120 GM PAIR", display: "HAND GLOVES RUBBER 120 GM PAIR", type: "OTHERS", uom: "PAIR", avgPrice: 5.0, category: "cleaning_supplies" },
  { norm: "HAND GLOVES RUBBER 90GM PAIR", display: "HAND GLOVES RUBBER 90GM PAIR", type: "OTHERS", uom: "PAIR", avgPrice: 6.25, category: "cleaning_supplies" },
  { norm: "HEAT RESISTANT SILICON SPATULA L346MM", display: "HEAT RESISTANT SILICON SPATULA L346MM", type: "OTHERS", uom: "PCS", avgPrice: 42.0, category: "cleaning_supplies" },
  { norm: "HOTDOG 6 PCS", display: "HOTDOG 6 PCS", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "HOTDOG 6 PCS(18X9)", display: "HOTDOG 6 PCS(18X9)", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "ICE CUBE 25 KG", display: "ICE CUBE 25 KG", type: "RM", uom: "KG", avgPrice: 4.6538, category: "other_rm" },
  { norm: "ICE CUBE 25KG", display: "ICE CUBE 25KG", type: "RM", uom: "KG", avgPrice: 0.5, category: "other_rm" },
  { norm: "IMPULSE SEALER FOR PP/PE BAG(METAL BODY)12\" 2PCS", display: "IMPULSE SEALER FOR PP/PE BAG(METAL BODY)12\" 2PCS", type: "OTHERS", uom: "PCS", avgPrice: 110.0, category: "cleaning_supplies" },
  { norm: "KITCHEN APRON(10X100PCS)", display: "KITCHEN APRON(10X100PCS)", type: "PACK", uom: "CRT", avgPrice: 24.024, category: "ppe_hygiene" },
  { norm: "LECITEM PUMPABLES 18KG", display: "LECITEM PUMPABLES 18KG", type: "OTHERS", uom: "KG", avgPrice: 19.4444, category: "cleaning_supplies" },
  { norm: "LIQUID COLOR ORANGE 190GM", display: "LIQUID COLOR ORANGE 190GM", type: "RM", uom: "KG", avgPrice: 40.0, category: "other_rm" },
  { norm: "MANGO JUICE -(SUPPLY TO SCHOOL)", display: "MANGO JUICE -(SUPPLY TO SCHOOL)", type: "OTHERS", uom: "CRT", avgPrice: 19.0, category: "cleaning_supplies" },
  { norm: "MAXI ROLL 2PLY 400GRM(1X6)", display: "MAXI ROLL 2PLY 400GRM(1X6)", type: "OTHERS", uom: "CRT", avgPrice: 16.5238, category: "cleaning_supplies" },
  { norm: "MILK BREAD 750 G", display: "MILK BREAD 750 G", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "MILK POWDER(25KG)", display: "MILK POWDER(25KG)", type: "RM", uom: "BAG", avgPrice: 125.9624, category: "dairy_eggs" },
  { norm: "MORNING ROLL", display: "MORNING ROLL", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "MORNING ROLL 25X40", display: "MORNING ROLL 25X40", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "MULTICEREAL FLOUR(25KG)", display: "MULTICEREAL FLOUR(25KG)", type: "RM", uom: "KG", avgPrice: 190.8, category: "flour" },
  { norm: "MUNNA BUTTER(20KG)(VEG SHORTNING)", display: "MUNNA BUTTER(20KG)(VEG SHORTNING)", type: "RM", uom: "CRT", avgPrice: 93.6568, category: "fats_oils" },
  { norm: "NON-WOVEN BLUE ASTRO CAP 1000PCS", display: "NON-WOVEN BLUE ASTRO CAP 1000PCS", type: "OTHERS", uom: "CRT", avgPrice: 280.0, category: "cleaning_supplies" },
  { norm: "OPEL MARGARINE 10KG", display: "OPEL MARGARINE 10KG", type: "RM", uom: "KG", avgPrice: 32.9545, category: "fats_oils" },
  { norm: "PALM OIL(17L)", display: "PALM OIL(17L)", type: "RM", uom: "PCS", avgPrice: 110.0, category: "fats_oils" },
  { norm: "PALM OIL(18L)", display: "PALM OIL(18L)", type: "RM", uom: "LTR", avgPrice: 43.714, category: "fats_oils" },
  { norm: "PAPER CAKE BOX -(SUPPLY TO SCHOOL)", display: "PAPER CAKE BOX -(SUPPLY TO SCHOOL)", type: "PACK", uom: "CRT", avgPrice: 60.0, category: "packaging_disposables" },
  { norm: "PAPER CUP(20X50 PCS)X6", display: "PAPER CUP(20X50 PCS)X6", type: "PACK", uom: "CRT", avgPrice: 26.0, category: "packaging_disposables" },
  { norm: "PAPER NAPKIN WHIT -(SUPPLY TO SCHOOL)", display: "PAPER NAPKIN WHIT -(SUPPLY TO SCHOOL)", type: "PACK", uom: "CRT", avgPrice: 45.0, category: "packaging_disposables" },
  { norm: "PASTRY NYLON BRUSH 60MM", display: "PASTRY NYLON BRUSH 60MM", type: "PACK", uom: "PCS", avgPrice: 30.0, category: "packaging_disposables" },
  { norm: "PLAIN MUFFIN PLASTIC ROLL", display: "PLAIN MUFFIN PLASTIC ROLL", type: "PACK", uom: "KG", avgPrice: 15.3333, category: "purchased_goods" },
  { norm: "PLAIN MUFFIN PLASTIC(10KG/ROLL)", display: "PLAIN MUFFIN PLASTIC(10KG/ROLL)", type: "PACK", uom: "BAG", avgPrice: 15.0, category: "purchased_goods" },
  { norm: "PLAIN WHITE CAKE BOX -(SUPPLY TO SCHOOL)", display: "PLAIN WHITE CAKE BOX -(SUPPLY TO SCHOOL)", type: "OTHERS", uom: "CRT", avgPrice: 43.5333, category: "cleaning_supplies" },
  { norm: "PLASTIC SHOE COVER BLUE 20*100PCS", display: "PLASTIC SHOE COVER BLUE 20*100PCS", type: "PACK", uom: "CRT", avgPrice: 130.0, category: "packaging_disposables" },
  { norm: "POTASIUM SORBATE(25KG)", display: "POTASIUM SORBATE(25KG)", type: "RM", uom: "KG", avgPrice: 28.0, category: "preservatives" },
  { norm: "POTASIUM SORBATE(5 KG*2)", display: "POTASIUM SORBATE(5 KG*2)", type: "RM", uom: "CRT", avgPrice: 352.0, category: "preservatives" },
  { norm: "PRINTED 2 SIDE BAG(ROTI)", display: "PRINTED 2 SIDE BAG(ROTI)", type: "OTHERS", uom: "KG", avgPrice: 13.0, category: "cleaning_supplies" },
  { norm: "RED COLOR BOTTLE FOSTER 6*12*28ML", display: "RED COLOR BOTTLE FOSTER 6*12*28ML", type: "OTHERS", uom: "CRT", avgPrice: 31.5, category: "cleaning_supplies" },
  { norm: "ROGANA POWDER(10KG)", display: "ROGANA POWDER(10KG)", type: "RM", uom: "BAG", avgPrice: 112.64, category: "leavening_improvers" },
  { norm: "ROSE WATER 500ML", display: "ROSE WATER 500ML", type: "RM", uom: "PCS", avgPrice: 3.0, category: "flavors_fillings" },
  { norm: "SALT(25KG)", display: "SALT(25KG)", type: "RM", uom: "BAG", avgPrice: 7.1969, category: "preservatives" },
  { norm: "SAPTULA STAINLESS STEEL 60MM", display: "SAPTULA STAINLESS STEEL 60MM", type: "RM", uom: "PCS", avgPrice: 29.0, category: "other_rm" },
  { norm: "SCAPER(STEEL MOP)", display: "SCAPER(STEEL MOP)", type: "OTHERS", uom: "PCS", avgPrice: 7.0, category: "cleaning_supplies" },
  { norm: "SCRAPERS STEEL 120*120MM", display: "SCRAPERS STEEL 120*120MM", type: "OTHERS", uom: "PCS", avgPrice: 33.0, category: "cleaning_supplies" },
  { norm: "SEALER M/C", display: "SEALER M/C", type: "OTHERS", uom: "", avgPrice: null, category: "cleaning_supplies" },
  { norm: "SEALER M/C 300MM PFS HD", display: "SEALER M/C 300MM PFS HD", type: "OTHERS", uom: "PCS", avgPrice: 250.0, category: "cleaning_supplies" },
  { norm: "SESAME SEEDS(15KG)", display: "SESAME SEEDS(15KG)", type: "RM", uom: "BAG", avgPrice: 74.5, category: "flavors_fillings" },
  { norm: "SESAME SEEDS(1KG)", display: "SESAME SEEDS(1KG)", type: "RM", uom: "KG", avgPrice: 13.08, category: "flavors_fillings" },
  { norm: "SESAME SEEDS(25KG)", display: "SESAME SEEDS(25KG)", type: "RM", uom: "KG", avgPrice: 13.0, category: "flavors_fillings" },
  { norm: "SHOE COVER 20*100S", display: "SHOE COVER 20*100S", type: "OTHERS", uom: "PCS", avgPrice: 0.08, category: "cleaning_supplies" },
  { norm: "SILICON WITH NYLON HANDLE L350MM", display: "SILICON WITH NYLON HANDLE L350MM", type: "PACK", uom: "PCS", avgPrice: 44.0, category: "ppe_hygiene" },
  { norm: "SOFT BRUSH(KNIFE)", display: "SOFT BRUSH(KNIFE)", type: "OTHERS", uom: "PCS", avgPrice: 69.0, category: "cleaning_supplies" },
  { norm: "SOLVENENT", display: "SOLVENENT", type: "OTHERS", uom: "PCS", avgPrice: 225.0, category: "cleaning_supplies" },
  { norm: "SOUS CHEF HAZELNUT 5KG", display: "SOUS CHEF HAZELNUT 5KG", type: "RM", uom: "PCS", avgPrice: 130.0, category: "flavors_fillings" },
  { norm: "SOUS CHEF PISTACHIO 1KG", display: "SOUS CHEF PISTACHIO 1KG", type: "OTHERS", uom: "KG", avgPrice: 70.0, category: "cleaning_supplies" },
  { norm: "STATIONARY ITEMS -(SUPPLY TO SCHOOL)", display: "STATIONARY ITEMS -(SUPPLY TO SCHOOL)", type: "OTHERS", uom: "PCS", avgPrice: 70.0, category: "cleaning_supplies" },
  { norm: "STEEL PLASTIC HANDLE", display: "STEEL PLASTIC HANDLE", type: "PACK", uom: "PCS", avgPrice: 54.0, category: "ppe_hygiene" },
  { norm: "STICKER -(SUPPLY TO SCHOOL)", display: "STICKER -(SUPPLY TO SCHOOL)", type: "PACK", uom: "PCS", avgPrice: 1.5, category: "packaging_disposables" },
  { norm: "STRAWBERRY FILLING(5KG*4)", display: "STRAWBERRY FILLING(5KG*4)", type: "RM", uom: "CRT", avgPrice: 60.9, category: "flavors_fillings" },
  { norm: "STROM HAND WASH LIQUID 4X5LTR", display: "STROM HAND WASH LIQUID 4X5LTR", type: "OTHERS", uom: "CRT", avgPrice: 32.0, category: "cleaning_supplies" },
  { norm: "SUGAR POWDER(50KG)", display: "SUGAR POWDER(50KG)", type: "RM", uom: "BAG", avgPrice: 86.8993, category: "sweeteners" },
  { norm: "SUGAR(50KG)", display: "SUGAR(50KG)", type: "RM", uom: "KG", avgPrice: 49.6754, category: "sweeteners" },
  { norm: "TAPLONE SHEET", display: "TAPLONE SHEET", type: "OTHERS", uom: "MTR", avgPrice: 95.0, category: "cleaning_supplies" },
  { norm: "TORTILA BREAD - SALESMAN)10X12S)", display: "TORTILA BREAD - SALESMAN)10X12S)", type: "PACK", uom: "CRT", avgPrice: 84.0, category: "purchased_goods" },
  { norm: "TORTILA BREAD(SALESMAN)10X12S)", display: "TORTILA BREAD(SALESMAN)10X12S)", type: "RM", uom: "CRT", avgPrice: 70.0, category: "other_rm" },
  { norm: "TORTILA(SUPPLY OF MINISTRY)", display: "TORTILA(SUPPLY OF MINISTRY)", type: "PACK", uom: "PCS", avgPrice: 70.0, category: "purchased_goods" },
  { norm: "TORTILA(SUPPLY TO YASMINE PALACE REST.)10X12S", display: "TORTILA(SUPPLY TO YASMINE PALACE REST.)10X12S", type: "PACK", uom: "CRT", avgPrice: 70.0, category: "purchased_goods" },
  { norm: "TUBE ROLL", display: "TUBE ROLL", type: "PACK", uom: "KG", avgPrice: 7.0, category: "packaging_disposables" },
  { norm: "TUTTY FRUTY MIX 15 KG", display: "TUTTY FRUTY MIX 15 KG", type: "RM", uom: "KG", avgPrice: 7.3333, category: "flavors_fillings" },
  { norm: "TUTTY FRUTY MIX(15KG)", display: "TUTTY FRUTY MIX(15KG)", type: "RM", uom: "BAG", avgPrice: 110.0, category: "flavors_fillings" },
  { norm: "VANILLA ESSENCE 28ML*12", display: "VANILLA ESSENCE 28ML*12", type: "RM", uom: "CRT", avgPrice: 6.2917, category: "flavors_fillings" },
  { norm: "VANILLA POWDER 10KG", display: "VANILLA POWDER 10KG", type: "RM", uom: "BAG", avgPrice: 253.4267, category: "flavors_fillings" },
  { norm: "VANILLA POWDER 1KG", display: "VANILLA POWDER 1KG", type: "RM", uom: "KG", avgPrice: 35.75, category: "flavors_fillings" },
  { norm: "VANILLA SLICE CAKE 65 G", display: "VANILLA SLICE CAKE 65 G", type: "RM", uom: "KG", avgPrice: 13.2, category: "flavors_fillings" },
  { norm: "VANILLA SLICE CAKE 65G(7X4)", display: "VANILLA SLICE CAKE 65G(7X4)", type: "PACK", uom: "KG", avgPrice: 13.0, category: "purchased_goods" },
  { norm: "VINEGAR(4L X 4)", display: "VINEGAR(4L X 4)", type: "OTHERS", uom: "LTR", avgPrice: 1.375, category: "cleaning_supplies" },
  { norm: "VINYL GLOVES(10X100P)L", display: "VINYL GLOVES(10X100P)L", type: "OTHERS", uom: "CRT", avgPrice: 27.05, category: "cleaning_supplies" },
  { norm: "VINYL GLOVES(12X100P)L", display: "VINYL GLOVES(12X100P)L", type: "OTHERS", uom: "CRT", avgPrice: 72.0, category: "cleaning_supplies" },
  { norm: "WHITE SUGER 50KG", display: "WHITE SUGER 50KG", type: "OTHERS", uom: "BAG", avgPrice: 102.0, category: "cleaning_supplies" },
  { norm: "ZATHER AL SALAM 1KG", display: "ZATHER AL SALAM 1KG", type: "RM", uom: "KG", avgPrice: 6.6, category: "flavors_fillings" },
  { norm: "ZATHER POWDER 1KG", display: "ZATHER POWDER 1KG", type: "RM", uom: "KG", avgPrice: 10.0, category: "flavors_fillings" },
  { norm: "ZATHER POWDER 5KG", display: "ZATHER POWDER 5KG", type: "RM", uom: "CRT", avgPrice: 45.0, category: "flavors_fillings" },
  { norm: "ZEDO PLUS(25KG)", display: "ZEDO PLUS(25KG)", type: "RM", uom: "BAG", avgPrice: 200.6667, category: "leavening_improvers" },
];

export const EXCEL_SUP_ITEMS: ExcelSupItem[] = [
  { supplier: "AL AJMERA", item: "BREAD IMPROVER(10KG)", uom: "BAG", avgPrice: 150.0, lastPrice: 150.0, count: 42 },
  { supplier: "AL AJMERA", item: "DATES PASTE(1KG*12)", uom: "CRT", avgPrice: 108.0, lastPrice: 108.0, count: 5 },
  { supplier: "AL AJMERA", item: "POTASIUM SORBATE(25KG)", uom: "KG", avgPrice: 28.0, lastPrice: 28.0, count: 1 },
  { supplier: "AL FONDOKIA", item: "BREAD WIRE 10KG PACK", uom: "CRT", avgPrice: 224.0, lastPrice: 32.0, count: 3 },
  { supplier: "AL SAFA", item: "CUP CAKE PAPER(1000 PCS)", uom: "PCS", avgPrice: 0.0095, lastPrice: 0.0095, count: 1 },
  { supplier: "AL SAFA", item: "CUP CAKE PAPER(1000 PCS)9CM", uom: "PKT", avgPrice: 9.51, lastPrice: 9.5, count: 2 },
  { supplier: "AL WAJBA", item: "CREAM CHEESE(1KG)", uom: "KG", avgPrice: 22.0, lastPrice: 22.0, count: 27 },
  { supplier: "AMOUDI", item: "1000395", uom: "KG", avgPrice: 11.5, lastPrice: 11.5, count: 1 },
  { supplier: "AMOUDI", item: "BROWN BREAD", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 5 },
  { supplier: "AMOUDI", item: "BROWN BREAD 25X40", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 2 },
  { supplier: "AMOUDI", item: "BURGER BUN 4 PCS", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 58 },
  { supplier: "AMOUDI", item: "BURGER BUN 4 PCS(10X12)", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 36 },
  { supplier: "AMOUDI", item: "BUTTER ROLL 12X9INCH", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 1 },
  { supplier: "AMOUDI", item: "BUTTER ROLL 300 G", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 1 },
  { supplier: "AMOUDI", item: "CHAPATHI PLASTIC", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 1 },
  { supplier: "AMOUDI", item: "CREAM BUN PLASTIC 10KG/ROLL", uom: "KG", avgPrice: 16.0, lastPrice: 16.0, count: 13 },
  { supplier: "AMOUDI", item: "CUP CAKE 65 G 10KG/ROLL", uom: "KG", avgPrice: 16.0, lastPrice: 16.0, count: 11 },
  { supplier: "AMOUDI", item: "DINNER ROLL", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 7 },
  { supplier: "AMOUDI", item: "HOTDOG 6 PCS", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 67 },
  { supplier: "AMOUDI", item: "HOTDOG 6 PCS(18X9)", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 38 },
  { supplier: "AMOUDI", item: "MILK BREAD 750 G", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 69 },
  { supplier: "AMOUDI", item: "MORNING ROLL", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 15 },
  { supplier: "AMOUDI", item: "MORNING ROLL 25X40", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 16 },
  { supplier: "AMOUDI", item: "PLAIN MUFFIN PLASTIC ROLL", uom: "KG", avgPrice: 15.3333, lastPrice: 15.0, count: 3 },
  { supplier: "AMOUDI", item: "PLAIN MUFFIN PLASTIC(10KG/ROLL)", uom: "BAG", avgPrice: 15.0, lastPrice: 15.0, count: 3 },
  { supplier: "AMOUDI", item: "PRINTED 2 SIDE BAG(ROTI)", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 5 },
  { supplier: "AMOUDI", item: "TUBE ROLL", uom: "KG", avgPrice: 7.0, lastPrice: 7.0, count: 2 },
  { supplier: "AMOUDI", item: "VANILLA SLICE CAKE 65 G", uom: "KG", avgPrice: 13.2, lastPrice: 13.0, count: 15 },
  { supplier: "AMOUDI", item: "VANILLA SLICE CAKE 65G(7X4)", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 6 },
  { supplier: "BRADMA", item: "FRESH EGG(1CTN X 360)", uom: "PCS", avgPrice: 0.5694, lastPrice: 0.6111, count: 2 },
  { supplier: "BRADMA", item: "SESAME SEEDS(15KG)", uom: "BAG", avgPrice: 140.0, lastPrice: 140.0, count: 1 },
  { supplier: "BRADMA", item: "SOUS CHEF HAZELNUT 5KG", uom: "PCS", avgPrice: 130.0, lastPrice: 130.0, count: 7 },
  { supplier: "BRADMA", item: "SOUS CHEF PISTACHIO 1KG", uom: "KG", avgPrice: 70.0, lastPrice: 70.0, count: 1 },
  { supplier: "BRADMA", item: "VANILLA POWDER 10KG", uom: "BAG", avgPrice: 390.0, lastPrice: 390.0, count: 1 },
  { supplier: "BRADMA", item: "ZATHER POWDER 1KG", uom: "KG", avgPrice: 10.0, lastPrice: 10.0, count: 3 },
  { supplier: "CASH", item: "APPLE -(SUPPLY TO SCHOOL)", uom: "CRT", avgPrice: 118.0, lastPrice: 118.0, count: 2 },
  { supplier: "CASH", item: "BISCUITES -(SUPPLY TO SCHOOL)", uom: "PACK", avgPrice: 9.5, lastPrice: 9.5, count: 2 },
  { supplier: "CASH", item: "CHOCOLATE -(SUPPLY TO SCHOOL)", uom: "PACK", avgPrice: 71.25, lastPrice: 183.0, count: 3 },
  { supplier: "CASH", item: "COOKIES MIX -(SUPPLY TO SCHOOL)", uom: "PCS", avgPrice: 1.1, lastPrice: 1.1, count: 1 },
  { supplier: "CASH", item: "COOKIES, BISCUITS & CHOCOLATES(SUPPLY TO SCHOOL EVENTS)", uom: "", avgPrice: null, lastPrice: null, count: 1 },
  { supplier: "CASH", item: "HAND GLOVES MEDICAL(VINYL)", uom: "PKT", avgPrice: 6.5, lastPrice: 6.5, count: 2 },
  { supplier: "CASH", item: "HAND GLOVES RUBBER 120 GM PAIR", uom: "PAIR", avgPrice: 5.0, lastPrice: 5.0, count: 2 },
  { supplier: "CASH", item: "HAND GLOVES RUBBER 90GM PAIR", uom: "PAIR", avgPrice: 5.0, lastPrice: 5.0, count: 2 },
  { supplier: "CASH", item: "IMPULSE SEALER FOR PP/PE BAG(METAL BODY)12\" 2PCS", uom: "PCS", avgPrice: 110.0, lastPrice: 110.0, count: 2 },
  { supplier: "CASH", item: "MANGO JUICE -(SUPPLY TO SCHOOL)", uom: "CRT", avgPrice: 19.0, lastPrice: 19.0, count: 1 },
  { supplier: "CASH", item: "PAPER CAKE BOX -(SUPPLY TO SCHOOL)", uom: "CRT", avgPrice: 60.0, lastPrice: 60.0, count: 1 },
  { supplier: "CASH", item: "PAPER NAPKIN WHIT -(SUPPLY TO SCHOOL)", uom: "CRT", avgPrice: 45.0, lastPrice: 45.0, count: 1 },
  { supplier: "CASH", item: "PLAIN WHITE CAKE BOX -(SUPPLY TO SCHOOL)", uom: "CRT", avgPrice: 43.5333, lastPrice: 0.6, count: 3 },
  { supplier: "CASH", item: "STATIONARY ITEMS -(SUPPLY TO SCHOOL)", uom: "PCS", avgPrice: 70.0, lastPrice: 70.0, count: 1 },
  { supplier: "CASH", item: "STICKER -(SUPPLY TO SCHOOL)", uom: "PCS", avgPrice: 1.5, lastPrice: 2.25, count: 2 },
  { supplier: "CASH/AL HADIDY", item: "HAND GLOVES BABY(10PAIR/PKT)", uom: "PKT", avgPrice: 7.0, lastPrice: 7.0, count: 1 },
  { supplier: "CASH/DELTA", item: "COTTON GLOVES 10PC/PKT", uom: "CRT", avgPrice: 280.0, lastPrice: 280.0, count: 4 },
  { supplier: "CASH/ROBBY", item: "CUP CAKE PAPER(16X1000PCS)9.5CM", uom: "CRT", avgPrice: 180.0, lastPrice: 180.0, count: 2 },
  { supplier: "CHEF", item: "CROISSANT BUTTER(10KG)", uom: "KG", avgPrice: 75.0, lastPrice: 75.0, count: 1 },
  { supplier: "DELTA", item: "SEALER M/C 300MM PFS HD", uom: "PCS", avgPrice: 250.0, lastPrice: 250.0, count: 1 },
  { supplier: "ETIHAD", item: "AREEJ MARGARINE(25KG)", uom: "BAG", avgPrice: 161.896, lastPrice: 11.8, count: 100 },
  { supplier: "ETIHAD", item: "FLOUR NO.1(50KG)(JAMILA)", uom: "KG", avgPrice: 22.68, lastPrice: 2.1, count: 5 },
  { supplier: "ETIHAD", item: "FLOUR NO.1(50KG)(TURKEY)", uom: "KG", avgPrice: 2.1, lastPrice: 2.1, count: 1 },
  { supplier: "ETIHAD", item: "GLUTEN(25KG)", uom: "BAG", avgPrice: 157.8476, lastPrice: 10.0, count: 63 },
  { supplier: "ETIHAD", item: "MILK POWDER(25KG)", uom: "BAG", avgPrice: 124.5009, lastPrice: 8.8, count: 115 },
  { supplier: "ETIHAD", item: "SESAME SEEDS(1KG)", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 49 },
  { supplier: "ETIHAD", item: "SESAME SEEDS(25KG)", uom: "KG", avgPrice: 13.0, lastPrice: 13.0, count: 9 },
  { supplier: "FIRDOUS", item: "PALM OIL(18L)", uom: "TIN", avgPrice: 79.0, lastPrice: 79.0, count: 1 },
  { supplier: "FORWARD GROUP", item: "ENGLSIH CAKE STICKER- ADJUSTED", uom: "PCS", avgPrice: 0.3, lastPrice: 0.3, count: 2 },
  { supplier: "GULF STREAM", item: "CALCIUM PROPIONATE(20KG)", uom: "BAG", avgPrice: 232.0161, lastPrice: 17.5, count: 31 },
  { supplier: "GULF STREAM", item: "POTASIUM SORBATE(5 KG*2)", uom: "CRT", avgPrice: 352.0, lastPrice: 55.0, count: 25 },
  { supplier: "HOLLANDI", item: "ANGLE BAKING POWDER(10KG)", uom: "BAG", avgPrice: 78.0, lastPrice: 78.0, count: 2 },
  { supplier: "HOLLANDI", item: "APPLE FILLING(2.7KG)", uom: "KG", avgPrice: 65.0, lastPrice: 65.0, count: 2 },
  { supplier: "HOLLANDI", item: "BAKERS KNIFE 65CM", uom: "PCS", avgPrice: 151.0, lastPrice: 151.0, count: 1 },
  { supplier: "HOLLANDI", item: "BAKING POWDER(10KG)", uom: "KG", avgPrice: 29.4, lastPrice: 7.8, count: 13 },
  { supplier: "HOLLANDI", item: "BAKING POWDER(25KG)", uom: "BAG", avgPrice: 78.0, lastPrice: 78.0, count: 1 },
  { supplier: "HOLLANDI", item: "BOTTLE AND CAN OPNER", uom: "PCS", avgPrice: 54.0, lastPrice: 54.0, count: 1 },
  { supplier: "HOLLANDI", item: "BREAD IMPROVER(15KG)", uom: "BAG", avgPrice: 161.9529, lastPrice: 17.3333, count: 99 },
  { supplier: "HOLLANDI", item: "CAKE GEL(1 PACK X 5KG)", uom: "CRT", avgPrice: 51.1579, lastPrice: 14.4, count: 19 },
  { supplier: "HOLLANDI", item: "CHOCKLATE FILLING(5KG)", uom: "KG", avgPrice: 43.7143, lastPrice: 18.0, count: 14 },
  { supplier: "HOLLANDI", item: "CHOCKLATE FILLING(5KG)8%", uom: "KG", avgPrice: 44.0, lastPrice: 22.0, count: 4 },
  { supplier: "HOLLANDI", item: "FLOUR(MULTICEREAL)(25KG)", uom: "BAG", avgPrice: 450.0, lastPrice: 450.0, count: 1 },
  { supplier: "HOLLANDI", item: "FOOD FLAVOR - BANANA 1LTR", uom: "PCS", avgPrice: 58.0, lastPrice: 58.0, count: 8 },
  { supplier: "HOLLANDI", item: "FOOD FLAVOR - ORANGE 1LTR", uom: "LTR", avgPrice: 53.5, lastPrice: 58.0, count: 4 },
  { supplier: "HOLLANDI", item: "GLUTEN(25KG)", uom: "KG", avgPrice: 8.0, lastPrice: 8.0, count: 3 },
  { supplier: "HOLLANDI", item: "HEAT RESISTANT SILICON SPATULA L346MM", uom: "PCS", avgPrice: 42.0, lastPrice: 42.0, count: 1 },
  { supplier: "HOLLANDI", item: "LIQUID COLOR ORANGE 190GM", uom: "KG", avgPrice: 40.0, lastPrice: 40.0, count: 1 },
  { supplier: "HOLLANDI", item: "MULTICEREAL FLOUR(25KG)", uom: "KG", avgPrice: 190.8, lastPrice: 18.0, count: 5 },
  { supplier: "HOLLANDI", item: "OPEL MARGARINE 10KG", uom: "KG", avgPrice: 32.9545, lastPrice: 12.5, count: 11 },
  { supplier: "HOLLANDI", item: "PASTRY NYLON BRUSH 60MM", uom: "PCS", avgPrice: 30.0, lastPrice: 30.0, count: 1 },
  { supplier: "HOLLANDI", item: "SAPTULA STAINLESS STEEL 60MM", uom: "PCS", avgPrice: 29.0, lastPrice: 29.0, count: 2 },
  { supplier: "HOLLANDI", item: "SCRAPERS STEEL 120*120MM", uom: "PCS", avgPrice: 33.0, lastPrice: 33.0, count: 2 },
  { supplier: "HOLLANDI", item: "SILICON WITH NYLON HANDLE L350MM", uom: "PCS", avgPrice: 44.0, lastPrice: 44.0, count: 1 },
  { supplier: "HOLLANDI", item: "SOFT BRUSH(KNIFE)", uom: "PCS", avgPrice: 69.0, lastPrice: 69.0, count: 1 },
  { supplier: "HOLLANDI", item: "STEEL PLASTIC HANDLE", uom: "PCS", avgPrice: 54.0, lastPrice: 54.0, count: 1 },
  { supplier: "HOLLANDI", item: "ZEDO PLUS(25KG)", uom: "BAG", avgPrice: 200.6667, lastPrice: 14.0, count: 99 },
  { supplier: "HOTPACK", item: "CUP CAKE PAPER(16X1000PCS)9.5CM", uom: "CRT", avgPrice: 330.0, lastPrice: 330.0, count: 1 },
  { supplier: "JANA INT. TRD.", item: "BLUE HAND SLEEVE 20*100PCS", uom: "CRT", avgPrice: 85.0, lastPrice: 85.0, count: 1 },
  { supplier: "JANA INT. TRD.", item: "BLUE NONWOVEN MOB CAP 10*100PCS", uom: "CRT", avgPrice: 30.0, lastPrice: 30.0, count: 1 },
  { supplier: "JANA INT. TRD.", item: "NON-WOVEN BLUE ASTRO CAP 1000PCS", uom: "CRT", avgPrice: 280.0, lastPrice: 280.0, count: 1 },
  { supplier: "JANA INT. TRD.", item: "PLASTIC SHOE COVER BLUE 20*100PCS", uom: "CRT", avgPrice: 130.0, lastPrice: 130.0, count: 1 },
  { supplier: "JEWAN", item: "CREAM CHEESE(1KG)", uom: "KG", avgPrice: 18.0, lastPrice: 18.0, count: 1 },
  { supplier: "JEWAN FOOD", item: "CREAM CHEESE(1KG)", uom: "KG", avgPrice: 18.0, lastPrice: 18.0, count: 1 },
  { supplier: "MAAS", item: "AREEJ MARGARINE(25KG)", uom: "KG", avgPrice: 7.92, lastPrice: 7.92, count: 1 },
  { supplier: "MAAS", item: "AREEJ MARGARINE/FERN BLENDED BUTTER(25KG)", uom: "KG", avgPrice: 7.96, lastPrice: 7.92, count: 2 },
  { supplier: "MAAS", item: "BAKING PAPER(1X500 PCS)", uom: "CRT", avgPrice: 39.889, lastPrice: 0.13, count: 31 },
  { supplier: "MAAS", item: "BAKING POWDER(10KG)", uom: "BAG", avgPrice: 64.04, lastPrice: 8.2, count: 5 },
  { supplier: "MAAS", item: "BLACK SEEDS", uom: "KG", avgPrice: 16.0, lastPrice: 16.0, count: 1 },
  { supplier: "MAAS", item: "BLEACH LIQUID 6X3.78 LTR CLOROX", uom: "CRT", avgPrice: 88.0, lastPrice: 88.0, count: 1 },
  { supplier: "MAAS", item: "BLEACH LIQUID 6X3.78LTR CLOROX", uom: "CRT", avgPrice: 88.0, lastPrice: 88.0, count: 1 },
  { supplier: "MAAS", item: "CHAKKI ATTA FLOUR(50KG)", uom: "KG", avgPrice: 24.408, lastPrice: 2.26, count: 15 },
  { supplier: "MAAS", item: "CHOCKLATE FILLING(5KG)", uom: "KG", avgPrice: 22.0, lastPrice: 22.0, count: 1 },
  { supplier: "MAAS", item: "CINNAMON POWDER(1KG)", uom: "KG", avgPrice: 20.0, lastPrice: 20.0, count: 1 },
  { supplier: "MAAS", item: "CINNAMON POWDER(5KG)", uom: "KG", avgPrice: 21.0, lastPrice: 21.0, count: 1 },
  { supplier: "MAAS", item: "CLING FILM 1X45CM 5KG(JMBO)", uom: "KG", avgPrice: 23.5556, lastPrice: 8.6, count: 9 },
  { supplier: "MAAS", item: "COTTON GLOVES 600 PAIR", uom: "CRT", avgPrice: 317.0808, lastPrice: 0.6833, count: 13 },
  { supplier: "MAAS", item: "CUP CAKE PAPER(16X1000PCS)9.5CM", uom: "CRT", avgPrice: 136.5, lastPrice: 135.0, count: 2 },
  { supplier: "MAAS", item: "CUP CAKE PAPER(25X1000 PCS)", uom: "PCS", avgPrice: 0.0084, lastPrice: 0.0084, count: 7 },
  { supplier: "MAAS", item: "DATES PASTE(5KG*3)", uom: "CRT", avgPrice: 70.5686, lastPrice: 8.0, count: 17 },
  { supplier: "MAAS", item: "FACE MASK 1X50PCS", uom: "BOX", avgPrice: 2.713, lastPrice: 0.065, count: 5 },
  { supplier: "MAAS", item: "FRESH EGG(1CTN X 360)", uom: "CRT", avgPrice: 112.675, lastPrice: 0.4306, count: 80 },
  { supplier: "MAAS", item: "GARBAGE BAG 124*140 10S", uom: "CRT", avgPrice: 38.0, lastPrice: 38.0, count: 9 },
  { supplier: "MAAS", item: "GARBAGE BAG 95*110 20PKT", uom: "CRT", avgPrice: 38.0, lastPrice: 38.0, count: 2 },
  { supplier: "MAAS", item: "GHEE(14L)", uom: "TIN", avgPrice: 96.0, lastPrice: 96.0, count: 18 },
  { supplier: "MAAS", item: "GHEE(15L)", uom: "TIN", avgPrice: 52.192, lastPrice: 6.2667, count: 25 },
  { supplier: "MAAS", item: "HAIR NET 10*100 PCS", uom: "CRT", avgPrice: 16.5165, lastPrice: 0.033, count: 6 },
  { supplier: "MAAS", item: "HAND GLOVES RUBBER 90GM PAIR", uom: "PAIR", avgPrice: 6.6071, lastPrice: 7.25, count: 7 },
  { supplier: "MAAS", item: "KITCHEN APRON(10X100PCS)", uom: "CRT", avgPrice: 24.024, lastPrice: 0.048, count: 4 },
  { supplier: "MAAS", item: "MAXI ROLL 2PLY 400GRM(1X6)", uom: "CRT", avgPrice: 16.6471, lastPrice: 16.0, count: 17 },
  { supplier: "MAAS", item: "PALM OIL(18L)", uom: "LTR", avgPrice: 30.3889, lastPrice: 4.2778, count: 80 },
  { supplier: "MAAS", item: "PAPER CUP(20X50 PCS)X6", uom: "CRT", avgPrice: 26.0, lastPrice: 26.0, count: 1 },
  { supplier: "MAAS", item: "SALT(25KG)", uom: "BAG", avgPrice: 7.1969, lastPrice: 0.48, count: 39 },
  { supplier: "MAAS", item: "SCAPER(STEEL MOP)", uom: "PCS", avgPrice: 7.0, lastPrice: 7.0, count: 1 },
  { supplier: "MAAS", item: "SESAME SEEDS(1KG)", uom: "KG", avgPrice: 17.0, lastPrice: 17.0, count: 1 },
  { supplier: "MAAS", item: "SHOE COVER 20*100S", uom: "PCS", avgPrice: 0.08, lastPrice: 0.08, count: 1 },
  { supplier: "MAAS", item: "STRAWBERRY FILLING(5KG*4)", uom: "CRT", avgPrice: 60.9, lastPrice: 5.8, count: 10 },
  { supplier: "MAAS", item: "STROM HAND WASH LIQUID 4X5LTR", uom: "CRT", avgPrice: 32.0, lastPrice: 32.0, count: 3 },
  { supplier: "MAAS", item: "SUGAR POWDER(50KG)", uom: "BAG", avgPrice: 106.5537, lastPrice: 2.84, count: 19 },
  { supplier: "MAAS", item: "SUGAR(50KG)", uom: "KG", avgPrice: 46.7802, lastPrice: 2.08, count: 92 },
  { supplier: "MAAS", item: "TORTILA BREAD - SALESMAN)10X12S)", uom: "CRT", avgPrice: 84.0, lastPrice: 98.0, count: 2 },
  { supplier: "MAAS", item: "TORTILA BREAD(SALESMAN)10X12S)", uom: "CRT", avgPrice: 70.0, lastPrice: 70.0, count: 6 },
  { supplier: "MAAS", item: "TORTILA(SUPPLY OF MINISTRY)", uom: "PCS", avgPrice: 70.0, lastPrice: 70.0, count: 1 },
  { supplier: "MAAS", item: "TORTILA(SUPPLY TO YASMINE PALACE REST.)10X12S", uom: "CRT", avgPrice: 70.0, lastPrice: 70.0, count: 15 },
  { supplier: "MAAS", item: "TUTTY FRUTY MIX 15 KG", uom: "KG", avgPrice: 7.3333, lastPrice: 7.3333, count: 1 },
  { supplier: "MAAS", item: "TUTTY FRUTY MIX(15KG)", uom: "BAG", avgPrice: 110.0, lastPrice: 110.0, count: 1 },
  { supplier: "MAAS", item: "VANILLA ESSENCE 28ML*12", uom: "PCS", avgPrice: 5.4762, lastPrice: 0.9583, count: 7 },
  { supplier: "MAAS", item: "VANILLA POWDER 10KG", uom: "BAG", avgPrice: 243.6714, lastPrice: 41.9, count: 14 },
  { supplier: "MAAS", item: "VINEGAR(4L X 4)", uom: "LTR", avgPrice: 1.375, lastPrice: 1.375, count: 9 },
  { supplier: "MAAS", item: "VINYL GLOVES(10X100P)L", uom: "CRT", avgPrice: 27.05, lastPrice: 0.05, count: 37 },
  { supplier: "PERFACT MEDIA", item: "TAPLONE SHEET", uom: "MTR", avgPrice: 95.0, lastPrice: 95.0, count: 1 },
  { supplier: "PRINT CARE", item: "CHINA PAPER STICKER 6CM*6CM 2", uom: "PCS", avgPrice: 0.093, lastPrice: 0.1, count: 10 },
  { supplier: "PROGRESSIVE", item: "FRESH EGG(1CTN X 360)", uom: "PCS", avgPrice: 0.4222, lastPrice: 0.4222, count: 2 },
  { supplier: "PROVENDER", item: "BAKELS BACOM A100 20KG", uom: "KG", avgPrice: 12.0, lastPrice: 12.0, count: 1 },
  { supplier: "PROVENDER", item: "LECITEM PUMPABLES 18KG", uom: "KG", avgPrice: 19.4444, lastPrice: 19.4444, count: 1 },
  { supplier: "QFM", item: "FINE BRAN FLOUR(10KG)", uom: "BAG", avgPrice: 22.0, lastPrice: 22.0, count: 1 },
  { supplier: "QFM", item: "FLOUR NO.1(50KG)", uom: "KG", avgPrice: 60.7289, lastPrice: 2.8, count: 90 },
  { supplier: "QFM", item: "PALM OIL(17L)", uom: "PCS", avgPrice: 110.0, lastPrice: 110.0, count: 3 },
  { supplier: "QFM", item: "PALM OIL(18L)", uom: "TIN", avgPrice: 77.0, lastPrice: 77.0, count: 23 },
  { supplier: "QFM", item: "SUGAR(50KG)", uom: "BAG", avgPrice: 102.0, lastPrice: 102.0, count: 6 },
  { supplier: "QFM", item: "WHITE SUGER 50KG", uom: "BAG", avgPrice: 102.0, lastPrice: 102.0, count: 5 },
  { supplier: "QNITED", item: "CROISSANT BUTTER(10KG)", uom: "KG", avgPrice: 65.4412, lastPrice: 12.5, count: 17 },
  { supplier: "QNITED", item: "ROGANA POWDER(10KG)", uom: "BAG", avgPrice: 112.64, lastPrice: 17.6, count: 5 },
  { supplier: "QRT", item: "SESAME SEEDS(15KG)", uom: "KG", avgPrice: 9.0, lastPrice: 9.0, count: 1 },
  { supplier: "RAMELIE", item: "SOLVENENT", uom: "PCS", avgPrice: 225.0, lastPrice: 305.0, count: 7 },
  { supplier: "RAWABI", item: "AREEJ MARGARINE(25KG)", uom: "BAG", avgPrice: 200.6, lastPrice: 11.8, count: 3 },
  { supplier: "RAWABI", item: "AREEJ MARGARINE(25KG)- UNSALTED", uom: "BAG", avgPrice: 200.0, lastPrice: 200.0, count: 5 },
  { supplier: "RAWABI", item: "BACKING BUTTER PAPER PLAIN 2*500", uom: "PCS", avgPrice: 0.05, lastPrice: 0.05, count: 1 },
  { supplier: "RAWABI", item: "BAKING BUTTER PAPER(1X500 PCS)", uom: "PCS", avgPrice: 0.24, lastPrice: 0.24, count: 1 },
  { supplier: "RAWABI", item: "BAKING POWDER(1KG)", uom: "PCS", avgPrice: 17.0, lastPrice: 17.0, count: 4 },
  { supplier: "RAWABI", item: "BUTTER BLOCK(25KG)- UNSALTED", uom: "BAG", avgPrice: 200.0, lastPrice: 200.0, count: 10 },
  { supplier: "RAWABI", item: "DATES PASTE(5KG*3)", uom: "CRT", avgPrice: 90.0, lastPrice: 90.0, count: 2 },
  { supplier: "RAWABI", item: "FLOUR NO.1(50KG)", uom: "BAG", avgPrice: 135.0, lastPrice: 135.0, count: 1 },
  { supplier: "RAWABI", item: "FRESH EGG(1CTN X 360)", uom: "CRT", avgPrice: 86.4229, lastPrice: 0.4306, count: 29 },
  { supplier: "RAWABI", item: "GARBAGE BAG 124*140 10S", uom: "CRT", avgPrice: 55.0, lastPrice: 55.0, count: 4 },
  { supplier: "RAWABI", item: "GARBAGE BAG 95*110 20PKT", uom: "CRT", avgPrice: 48.0, lastPrice: 48.0, count: 4 },
  { supplier: "RAWABI", item: "MAXI ROLL 2PLY 400GRM(1X6)", uom: "CRT", avgPrice: 16.0, lastPrice: 16.0, count: 4 },
  { supplier: "RAWABI", item: "PALM OIL(18L)", uom: "PCS", avgPrice: 110.0, lastPrice: 110.0, count: 4 },
  { supplier: "RAWABI", item: "RED COLOR BOTTLE FOSTER 6*12*28ML", uom: "CRT", avgPrice: 31.5, lastPrice: 31.5, count: 1 },
  { supplier: "RAWABI", item: "ROSE WATER 500ML", uom: "PCS", avgPrice: 3.0, lastPrice: 3.0, count: 1 },
  { supplier: "RAWABI", item: "SUGAR POWDER(50KG)", uom: "KG", avgPrice: 45.4067, lastPrice: 2.6, count: 9 },
  { supplier: "RAWABI", item: "SUGAR(50KG)", uom: "KG", avgPrice: 2.08, lastPrice: 2.08, count: 1 },
  { supplier: "RAWABI", item: "VANILLA ESSENCE 28ML*12", uom: "CRT", avgPrice: 12.0, lastPrice: 12.0, count: 1 },
  { supplier: "RAWABI", item: "VANILLA POWDER 1KG", uom: "KG", avgPrice: 35.75, lastPrice: 47.0, count: 4 },
  { supplier: "RAWABI", item: "VINYL GLOVES(12X100P)L", uom: "CRT", avgPrice: 72.0, lastPrice: 72.0, count: 1 },
  { supplier: "RAWABI", item: "ZATHER AL SALAM 1KG", uom: "KG", avgPrice: 6.6, lastPrice: 6.6, count: 1 },
  { supplier: "RAWABI", item: "ZATHER POWDER 5KG", uom: "CRT", avgPrice: 45.0, lastPrice: 45.0, count: 1 },
  { supplier: "REALPACK", item: "ENGLISH CAKE TRAY/PAN CAKE 1000PCS", uom: "PCS", avgPrice: 0.56, lastPrice: 0.56, count: 2 },
  { supplier: "REALPACK", item: "ENGLISH CAKE TRAY/PAN CAKE 800PCS", uom: "PCS", avgPrice: 0.56, lastPrice: 0.56, count: 1 },
  { supplier: "ROYAL PACK", item: "CUP CAKE PAPER(12X1000PCS)9.5CM", uom: "CRT", avgPrice: 145.0, lastPrice: 145.0, count: 2 },
  { supplier: "ROYAL PACK", item: "CUP CAKE PAPER(16X1000PCS)9.5CM", uom: "CRT", avgPrice: 145.0, lastPrice: 145.0, count: 2 },
  { supplier: "SANA FOOD", item: "CHAPATI - RADISSON BLUE HOTEL", uom: "PKT", avgPrice: 1.1786, lastPrice: 0.25, count: 14 },
  { supplier: "SEA SHORE", item: "SEALER M/C", uom: "", avgPrice: null, lastPrice: null, count: 1 },
  { supplier: "VALENCIA", item: "APPLE FILLING(2.7KG)", uom: "KG", avgPrice: 40.7619, lastPrice: 22.8407, count: 13 },
  { supplier: "VALENCIA", item: "BREAD IMPROVER(10KG)", uom: "BAG", avgPrice: 185.0, lastPrice: 185.0, count: 2 },
  { supplier: "VALENCIA", item: "DRY YEAST(500G X 20)", uom: "CRT", avgPrice: 72.0212, lastPrice: 11.5, count: 118 },
  { supplier: "VALENCIA", item: "GLUTEN(25KG)", uom: "BAG", avgPrice: 144.7045, lastPrice: 9.8, count: 67 },
  { supplier: "VALENCIA", item: "MILK POWDER(25KG)", uom: "BAG", avgPrice: 210.0, lastPrice: 210.0, count: 2 },
  { supplier: "VALENCIA", item: "MUNNA BUTTER(20KG)(VEG SHORTNING)", uom: "CRT", avgPrice: 93.6568, lastPrice: 7.25, count: 110 },
  { supplier: "VERSA", item: "CREAM CHEESE(1KG)", uom: "KG", avgPrice: 22.0, lastPrice: 22.0, count: 2 },
  { supplier: "WEST BAY", item: "ICE CUBE 25 KG", uom: "KG", avgPrice: 4.6538, lastPrice: 0.5, count: 26 },
  { supplier: "WEST BAY", item: "ICE CUBE 25KG", uom: "KG", avgPrice: 0.5, lastPrice: 0.5, count: 1 },
];