import { mutation, query } from "./_generated/server";
import { v } from "convex/values";
import {
  validatePeriodOpen,
  validateJournalBalance,
  generateDocumentNumber,
  postJournalEntry,
  reverseJournalEntry,
  JournalLineInput,
} from "./lib/posting";
import { assertPeriodOpen } from "./lib/fiscalControl";

// ─── CREATE MANUAL JOURNAL ENTRY ──────────────────────────────────────────────

export const createManualJournalEntry = mutation({
  args: {
    companyId: v.id("companies"),
    branchId: v.id("branches"),
    journalType: v.union(
      v.literal("general"),
      v.literal("cash"),
      v.literal("expenses"),
      v.literal("adjustments")
    ),
    entryDate: v.string(),
    periodId: v.id("accountingPeriods"),
    currencyId: v.id("currencies"),
    exchangeRate: v.number(),
    costCenterId: v.optional(v.id("costCenters")),
    description: v.string(),
    notes: v.optional(v.string()),
    createdBy: v.id("users"),
    lines: v.array(
      v.object({
        accountId: v.id("accounts"),
        subAccountType: v.optional(v.string()),
        subAccountId: v.optional(v.string()),
        description: v.optional(v.string()),
        costCenterId: v.optional(v.id("costCenters")),
        documentRef: v.optional(v.string()),
        debit: v.number(),
        credit: v.number(),
      })
    ),
  },
  handler: async (ctx, args) => {
    if (args.lines.length === 0) {
      throw new Error("يجب إضافة سطر واحد على الأقل في القيد");
    }

    await validatePeriodOpen(ctx, args.periodId);
    await assertPeriodOpen(ctx, args.entryDate, args.companyId);

    const fiscalYear = await ctx.db
      .query("fiscalYears")
      .withIndex("by_company", (q) => q.eq("companyId", args.companyId))
      .filter((q) => q.eq(q.field("status"), "open"))
      .first();

    let entryNumber = `JE-DRAFT-${Date.now()}`;
    if (fiscalYear) {
      entryNumber = await generateDocumentNumber(
        ctx,
        args.branchId,
        fiscalYear._id,
        "JE"
      );
    }

    let totalDebit = 0;
    let totalCredit = 0;
    for (const line of args.lines) {
      totalDebit += line.debit;
      totalCredit += line.credit;
    }

    const entryId = await ctx.db.insert("journalEntries", {
      companyId: args.companyId,
      branchId: args.branchId,
      entryNumber,
      journalType: args.journalType,
      entryDate: args.entryDate,
      periodId: args.periodId,
      currencyId: args.currencyId,
      exchangeRate: args.exchangeRate,
      costCenterId: args.costCenterId,
      description: args.description,
      totalDebit,
      totalCredit,
      postingStatus: "draft",
      isAutoGenerated: false,
      isReversingEntry: false,
      notes: args.notes,
      createdBy: args.createdBy,
      createdAt: Date.now(),
    });

    for (let i = 0; i < args.lines.length; i++) {
      const line = args.lines[i];
      await ctx.db.insert("journalLines", {
        entryId,
        lineNumber: i + 1,
        accountId: line.accountId,
        subAccountType: line.subAccountType,
        subAccountId: line.subAccountId,
        description: line.description,
        costCenterId: line.costCenterId,
        documentRef: line.documentRef,
        debit: line.debit,
        credit: line.credit,
        foreignDebit: 0,
        foreignCredit: 0,
      });
    }

    return { entryId, entryNumber };
  },
});

// ─── POST MANUAL JOURNAL ENTRY ────────────────────────────────────────────────

export const postManualJournalEntry = mutation({
  args: {
    entryId: v.id("journalEntries"),
    userId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const entry = await ctx.db.get(args.entryId);
    if (!entry) throw new Error("القيد غير موجود");
    if (entry.postingStatus !== "draft") {
      throw new Error("يمكن ترحيل القيود في وضع المسودة فقط");
    }
    if (entry.isAutoGenerated) {
      throw new Error("لا يمكن ترحيل القيود التلقائية يدوياً");
    }

    await validatePeriodOpen(ctx, entry.periodId);

    // Get lines and validate balance
    const lines = await ctx.db
      .query("journalLines")
      .withIndex("by_entry", (q) => q.eq("entryId", args.entryId))
      .collect();

    const lineInputs: JournalLineInput[] = lines.map((l) => ({
      accountId: l.accountId,
      debit: l.debit,
      credit: l.credit,
    }));

    validateJournalBalance(lineInputs);

    // Validate all accounts are postable
    for (const line of lines) {
      const account = await ctx.db.get(line.accountId);
      if (!account?.isPostable) {
        throw new Error(
          `الحساب "${account?.nameAr ?? line.accountId}" غير قابل للترحيل`
        );
      }
    }

    await ctx.db.patch(args.entryId, {
      postingStatus: "posted",
      postedBy: args.userId,
      postedAt: Date.now(),
    });

    return { success: true };
  },
});

// ─── REVERSE JOURNAL ENTRY ────────────────────────────────────────────────────

export const reverseJournalEntryMutation = mutation({
  args: {
    entryId: v.id("journalEntries"),
    userId: v.id("users"),
    reversalDate: v.string(),
    reversalPeriodId: v.id("accountingPeriods"),
  },
  handler: async (ctx, args) => {
    const reversalId = await reverseJournalEntry(
      ctx,
      args.entryId,
      args.reversalDate,
      args.reversalPeriodId,
      args.userId
    );
    return { success: true, reversalEntryId: reversalId };
  },
});

export const deleteDraftJournalEntry = mutation({
  args: {
    entryId: v.id("journalEntries"),
    userId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const entry = await ctx.db.get(args.entryId);
    if (!entry) throw new Error("القيد غير موجود");
    if (entry.postingStatus !== "draft") {
      throw new Error("يمكن حذف القيود المسودة فقط");
    }
    if (entry.isAutoGenerated) {
      throw new Error("لا يمكن حذف قيد تلقائي");
    }

    const lines = await ctx.db
      .query("journalLines")
      .withIndex("by_entry", (q) => q.eq("entryId", args.entryId))
      .collect();

    for (const line of lines) {
      await ctx.db.delete(line._id);
    }
    await ctx.db.delete(args.entryId);
    return { success: true };
  },
});

// ─── GET JOURNAL ENTRY ────────────────────────────────────────────────────────

export const getJournalEntry = query({
  args: { entryId: v.id("journalEntries") },
  handler: async (ctx, args) => {
    const entry = await ctx.db.get(args.entryId);
    if (!entry) return null;

    const lines = await ctx.db
      .query("journalLines")
      .withIndex("by_entry", (q) => q.eq("entryId", args.entryId))
      .collect();

    const enrichedLines = await Promise.all(
      lines.map(async (line) => {
        const account = await ctx.db.get(line.accountId);
        const costCenter = line.costCenterId
          ? await ctx.db.get(line.costCenterId)
          : null;
        return { ...line, account, costCenter };
      })
    );

    const branch = await ctx.db.get(entry.branchId);
    const period = await ctx.db.get(entry.periodId);

    return { ...entry, lines: enrichedLines, branch, period };
  },
});

// ─── LIST JOURNAL ENTRIES ─────────────────────────────────────────────────────

export const listJournalEntries = query({
  args: {
    branchId: v.optional(v.id("branches")),
    fromDate: v.optional(v.string()),
    toDate: v.optional(v.string()),
    journalType: v.optional(v.string()),
    postingStatus: v.optional(v.string()),
    periodId: v.optional(v.id("accountingPeriods")),
  },
  handler: async (ctx, args) => {
    let entries = args.branchId
      ? await ctx.db
          .query("journalEntries")
          .withIndex("by_branch", (q) => q.eq("branchId", args.branchId!))
          .collect()
      : await ctx.db.query("journalEntries").collect();

    if (args.fromDate) {
      entries = entries.filter((e) => e.entryDate >= args.fromDate!);
    }
    if (args.toDate) {
      entries = entries.filter((e) => e.entryDate <= args.toDate!);
    }
    if (args.journalType) {
      entries = entries.filter((e) => e.journalType === args.journalType);
    }
    if (args.postingStatus) {
      entries = entries.filter((e) => e.postingStatus === args.postingStatus);
    }
    if (args.periodId) {
      entries = entries.filter((e) => e.periodId === args.periodId);
    }

    entries.sort((a, b) => b.entryDate.localeCompare(a.entryDate));

    return entries;
  },
});

// ─── LIST BY COMPANY ──────────────────────────────────────────────────────────

export const listByCompany = query({
  args: {
    companyId: v.id("companies"),
    branchId: v.optional(v.id("branches")),
    fromDate: v.optional(v.string()),
    toDate: v.optional(v.string()),
    journalType: v.optional(v.string()),
    postingStatus: v.optional(
      v.union(v.literal("draft"), v.literal("posted"), v.literal("reversed"))
    ),
  },
  handler: async (ctx, args) => {
    const all = await ctx.db
      .query("journalEntries")
      .filter((q) => q.eq(q.field("companyId"), args.companyId))
      .order("desc")
      .take(200);

    return all.filter((j) => {
      if (args.branchId && j.branchId !== args.branchId) return false;
      if (args.fromDate && j.entryDate < args.fromDate) return false;
      if (args.toDate && j.entryDate > args.toDate) return false;
      if (args.journalType && j.journalType !== args.journalType) return false;
      if (args.postingStatus && j.postingStatus !== args.postingStatus) return false;
      return true;
    });
  },
});

// ─── CREATE MANUAL (with optional immediate post) ─────────────────────────────

export const createManual = mutation({
  args: {
    companyId: v.id("companies"),
    branchId: v.id("branches"),
    journalType: v.union(
      v.literal("general"),
      v.literal("cash"),
      v.literal("expenses"),
      v.literal("adjustments"),
      v.literal("opening")
    ),
    entryDate: v.string(),
    periodId: v.id("accountingPeriods"),
    currencyId: v.id("currencies"),
    costCenterId: v.optional(v.id("costCenters")),
    description: v.string(),
    notes: v.optional(v.string()),
    createdBy: v.id("users"),
    lines: v.array(
      v.object({
        accountId: v.id("accounts"),
        description: v.optional(v.string()),
        costCenterId: v.optional(v.id("costCenters")),
        debit: v.number(),
        credit: v.number(),
      })
    ),
    postImmediately: v.boolean(),
  },
  handler: async (ctx, args) => {
    if (args.lines.length === 0) {
      throw new Error("يجب إضافة سطر واحد على الأقل في القيد");
    }

    await validatePeriodOpen(ctx, args.periodId);

    if (args.postImmediately) {
      validateJournalBalance(
        args.lines.map((l) => ({ accountId: l.accountId, debit: l.debit, credit: l.credit }))
      );
    }

    const fiscalYear = await ctx.db
      .query("fiscalYears")
      .withIndex("by_company", (q) => q.eq("companyId", args.companyId))
      .filter((q) => q.eq(q.field("status"), "open"))
      .first();

    let entryNumber = `JE-DRAFT-${Date.now()}`;
    if (fiscalYear) {
      entryNumber = await generateDocumentNumber(ctx, args.branchId, fiscalYear._id, "JE");
    }

    const totalDebit = args.lines.reduce((s, l) => s + l.debit, 0);
    const totalCredit = args.lines.reduce((s, l) => s + l.credit, 0);

    const entryId = await ctx.db.insert("journalEntries", {
      companyId: args.companyId,
      branchId: args.branchId,
      entryNumber,
      journalType: args.journalType,
      entryDate: args.entryDate,
      periodId: args.periodId,
      currencyId: args.currencyId,
      exchangeRate: 1,
      costCenterId: args.costCenterId,
      description: args.description,
      totalDebit,
      totalCredit,
      postingStatus: args.postImmediately ? "posted" : "draft",
      isAutoGenerated: false,
      isReversingEntry: false,
      notes: args.notes,
      createdBy: args.createdBy,
      createdAt: Date.now(),
      ...(args.postImmediately
        ? { postedBy: args.createdBy, postedAt: Date.now() }
        : {}),
    });

    for (let i = 0; i < args.lines.length; i++) {
      await ctx.db.insert("journalLines", {
        entryId,
        lineNumber: i + 1,
        accountId: args.lines[i].accountId,
        description: args.lines[i].description,
        costCenterId: args.lines[i].costCenterId,
        debit: args.lines[i].debit,
        credit: args.lines[i].credit,
        foreignDebit: 0,
        foreignCredit: 0,
      });
    }

    return { entryId, entryNumber };
  },
});
