import { mutation, query } from "./_generated/server";
import { v } from "convex/values";
import {
  validatePeriodOpen,
  generateDocumentNumber,
  postJournalEntry,
  reverseJournalEntry,
  buildCashReceiptJournal,
  buildCashPaymentJournal,
} from "./lib/posting";
import { assertUserPermission, assertUserBranch } from "./lib/permissions";
import { logAudit } from "./lib/audit";
import { assertPeriodOpen } from "./lib/fiscalControl";

// ─── CASH RECEIPT VOUCHERS ────────────────────────────────────────────────────

export const createCashReceiptVoucher = mutation({
  args: {
    companyId: v.id("companies"),
    branchId: v.id("branches"),
    voucherDate: v.string(),
    periodId: v.id("accountingPeriods"),
    receivedFrom: v.string(),
    customerId: v.optional(v.id("customers")),
    receiptType: v.union(
      v.literal("customer_payment"),
      v.literal("other_receipt")
    ),
    cashAccountId: v.id("accounts"),
    amount: v.number(),
    currencyId: v.id("currencies"),
    exchangeRate: v.number(),
    paymentMethod: v.union(
      v.literal("cash"),
      v.literal("transfer"),
      v.literal("card"),
      v.literal("cheque")
    ),
    reference: v.optional(v.string()),
    costCenterId: v.optional(v.id("costCenters")),
    forMonth: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdBy: v.id("users"),
  },
  handler: async (ctx, args) => {
    // Permission check before any DB writes
    const user = await assertUserPermission(ctx, args.createdBy, "treasury", "create");
    assertUserBranch(user, args.branchId);

    await validatePeriodOpen(ctx, args.periodId);
    await assertPeriodOpen(ctx, args.voucherDate, args.companyId);

    const fiscalYear = await ctx.db
      .query("fiscalYears")
      .withIndex("by_company", (q) => q.eq("companyId", args.companyId))
      .filter((q) => q.eq(q.field("status"), "open"))
      .first();

    let voucherNumber = `CRV-${Date.now()}`;
    if (fiscalYear) {
      voucherNumber = await generateDocumentNumber(ctx, args.branchId, fiscalYear._id, "CRV");
    }

    const voucherId = await ctx.db.insert("cashReceiptVouchers", {
      companyId: args.companyId,
      branchId: args.branchId,
      voucherNumber,
      voucherDate: args.voucherDate,
      periodId: args.periodId,
      receivedFrom: args.receivedFrom,
      customerId: args.customerId,
      receiptType: args.receiptType,
      cashAccountId: args.cashAccountId,
      amount: args.amount,
      currencyId: args.currencyId,
      exchangeRate: args.exchangeRate,
      paymentMethod: args.paymentMethod,
      reference: args.reference,
      costCenterId: args.costCenterId,
      forMonth: args.forMonth,
      documentStatus: "draft" as const,
      postingStatus: "unposted" as const,
      allocationStatus: "unallocated" as const,
      notes: args.notes,
      createdBy: args.createdBy,
      createdAt: Date.now(),
    });

    await logAudit(ctx, {
      companyId: args.companyId,
      userId: args.createdBy,
      action: "create",
      module: "treasury",
      documentType: "cashReceiptVoucher",
      documentId: String(voucherId),
    });

    return { voucherId, voucherNumber };
  },
});

export const postCashReceiptVoucher = mutation({
  args: {
    voucherId: v.id("cashReceiptVouchers"),
    userId: v.id("users"),
    arAccountId: v.id("accounts"),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند القبض غير موجود");
    if (voucher.postingStatus === "posted") throw new Error("السند مرحل مسبقاً");

    await validatePeriodOpen(ctx, voucher.periodId);

    const journalLines = buildCashReceiptJournal(
      {
        _id: voucher._id,
        voucherNumber: voucher.voucherNumber,
        cashAccountId: voucher.cashAccountId,
        amount: voucher.amount,
        customerId: voucher.customerId,
        receiptType: voucher.receiptType,
      },
      args.arAccountId
    );

    const journalEntryId = await postJournalEntry(
      ctx,
      {
        companyId: voucher.companyId,
        branchId: voucher.branchId,
        journalType: "auto_receipt",
        entryDate: voucher.voucherDate,
        periodId: voucher.periodId,
        currencyId: voucher.currencyId,
        exchangeRate: voucher.exchangeRate,
        sourceType: "cashReceiptVoucher",
        sourceId: voucher._id,
        description: `Cash Receipt / سند قبض - ${voucher.voucherNumber}`,
        isAutoGenerated: true,
        createdBy: args.userId,
      },
      journalLines
    );

    await ctx.db.patch(args.voucherId, {
      postingStatus: "posted",
      documentStatus: "approved",
      journalEntryId,
    });

    return { success: true, journalEntryId };
  },
});

export const allocateReceipt = mutation({
  args: {
    voucherId: v.id("cashReceiptVouchers"),
    userId: v.id("users"),
    allocations: v.array(
      v.object({
        invoiceId: v.id("salesInvoices"),
        amount: v.number(),
      })
    ),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند القبض غير موجود");
    if (voucher.postingStatus !== "posted") {
      throw new Error("يجب ترحيل سند القبض أولاً");
    }

    // Check existing allocations
    const existingAllocations = await ctx.db
      .query("receiptAllocations")
      .withIndex("by_voucher", (q) => q.eq("voucherId", args.voucherId))
      .filter((q) => q.eq(q.field("isReversed"), false))
      .collect();

    const alreadyAllocated = existingAllocations.reduce(
      (s, a) => s + a.allocatedAmount,
      0
    );
    const newAllocationTotal = args.allocations.reduce((s, a) => s + a.amount, 0);

    if (alreadyAllocated + newAllocationTotal > voucher.amount) {
      throw new Error(
        `المبلغ المخصص (${(newAllocationTotal / 100).toFixed(2)}) يتجاوز الرصيد المتاح في السند`
      );
    }

    const today = new Date().toISOString().split("T")[0];

    for (const alloc of args.allocations) {
      const invoice = await ctx.db.get(alloc.invoiceId);
      if (!invoice) throw new Error(`الفاتورة ${alloc.invoiceId} غير موجودة`);

      await ctx.db.insert("receiptAllocations", {
        voucherId: args.voucherId,
        invoiceId: alloc.invoiceId,
        allocatedAmount: alloc.amount,
        allocationDate: today,
        createdBy: args.userId,
        createdAt: Date.now(),
        isReversed: false,
      });

      // Update invoice payment status
      const allInvoiceAllocations = await ctx.db
        .query("receiptAllocations")
        .withIndex("by_invoice", (q) => q.eq("invoiceId", alloc.invoiceId))
        .filter((q) => q.eq(q.field("isReversed"), false))
        .collect();

      const totalAllocated =
        allInvoiceAllocations.reduce((s, a) => s + a.allocatedAmount, 0) +
        alloc.amount;

      let paymentStatus: "unpaid" | "partial" | "paid" = "unpaid";
      if (totalAllocated >= invoice.totalAmount) {
        paymentStatus = "paid";
      } else if (totalAllocated > 0) {
        paymentStatus = "partial";
      }

      await ctx.db.patch(alloc.invoiceId, { paymentStatus });
    }

    // Update voucher allocation status
    const totalAllocatedNow = alreadyAllocated + newAllocationTotal;
    let allocationStatus: "unallocated" | "partial" | "fully_allocated" =
      "unallocated";
    if (totalAllocatedNow >= voucher.amount) {
      allocationStatus = "fully_allocated";
    } else if (totalAllocatedNow > 0) {
      allocationStatus = "partial";
    }

    await ctx.db.patch(args.voucherId, { allocationStatus });

    return { success: true };
  },
});

export const cancelCashReceiptVoucher = mutation({
  args: {
    voucherId: v.id("cashReceiptVouchers"),
    userId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند القبض غير موجود");
    if (voucher.postingStatus === "posted") {
      throw new Error("لا يمكن إلغاء سند قبض مرحل");
    }
    const user = await assertUserPermission(ctx, args.userId, "treasury", "edit");
    assertUserBranch(user, voucher.branchId);
    await ctx.db.patch(args.voucherId, { documentStatus: "cancelled" });
    return { success: true };
  },
});

export const deleteDraftCashReceiptVoucher = mutation({
  args: {
    voucherId: v.id("cashReceiptVouchers"),
    userId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند القبض غير موجود");
    if (voucher.documentStatus !== "draft" || voucher.postingStatus !== "unposted") {
      throw new Error("يمكن حذف مسودات سندات القبض فقط");
    }
    const user = await assertUserPermission(ctx, args.userId, "treasury", "delete");
    assertUserBranch(user, voucher.branchId);
    await ctx.db.delete(args.voucherId);
    return { success: true };
  },
});

export const reverseCashReceiptVoucher = mutation({
  args: {
    voucherId: v.id("cashReceiptVouchers"),
    userId: v.id("users"),
    reversalDate: v.string(),
    reversalPeriodId: v.id("accountingPeriods"),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند القبض غير موجود");
    if (voucher.postingStatus !== "posted") {
      throw new Error("يمكن عكس سندات القبض المرحلة فقط");
    }
    if (!voucher.journalEntryId) {
      throw new Error("لا يوجد قيد محاسبي مرتبط بسند القبض");
    }

    const allocations = await ctx.db
      .query("receiptAllocations")
      .withIndex("by_voucher_active", (q) => q.eq("voucherId", args.voucherId).eq("isReversed", false))
      .collect();
    if (allocations.length > 0) {
      throw new Error("لا يمكن عكس سند قبض عليه تخصيصات. قم بعكس التخصيصات أولاً");
    }

    await reverseJournalEntry(ctx, voucher.journalEntryId, args.reversalDate, args.reversalPeriodId, args.userId);
    await ctx.db.patch(args.voucherId, { postingStatus: "reversed" });
    return { success: true };
  },
});

// ─── CASH PAYMENT VOUCHERS ────────────────────────────────────────────────────

export const createCashPaymentVoucher = mutation({
  args: {
    companyId: v.id("companies"),
    branchId: v.id("branches"),
    voucherDate: v.string(),
    periodId: v.id("accountingPeriods"),
    paidTo: v.string(),
    supplierId: v.optional(v.id("suppliers")),
    paymentType: v.union(
      v.literal("supplier_payment"),
      v.literal("expense_payment"),
      v.literal("other")
    ),
    cashAccountId: v.id("accounts"),
    amount: v.number(),
    currencyId: v.id("currencies"),
    exchangeRate: v.number(),
    paymentMethod: v.union(
      v.literal("cash"),
      v.literal("transfer"),
      v.literal("cheque")
    ),
    reference: v.optional(v.string()),
    costCenterId: v.optional(v.id("costCenters")),
    notes: v.optional(v.string()),
    createdBy: v.id("users"),
  },
  handler: async (ctx, args) => {
    // Permission check before any DB writes
    const cpvUser = await assertUserPermission(ctx, args.createdBy, "treasury", "create");
    assertUserBranch(cpvUser, args.branchId);

    await validatePeriodOpen(ctx, args.periodId);
    await assertPeriodOpen(ctx, args.voucherDate, args.companyId);

    const fiscalYear = await ctx.db
      .query("fiscalYears")
      .withIndex("by_company", (q) => q.eq("companyId", args.companyId))
      .filter((q) => q.eq(q.field("status"), "open"))
      .first();

    let voucherNumber = `CPV-${Date.now()}`;
    if (fiscalYear) {
      voucherNumber = await generateDocumentNumber(ctx, args.branchId, fiscalYear._id, "CPV");
    }

    const voucherId = await ctx.db.insert("cashPaymentVouchers", {
      companyId: args.companyId,
      branchId: args.branchId,
      voucherNumber,
      voucherDate: args.voucherDate,
      periodId: args.periodId,
      paidTo: args.paidTo,
      supplierId: args.supplierId,
      paymentType: args.paymentType,
      cashAccountId: args.cashAccountId,
      amount: args.amount,
      currencyId: args.currencyId,
      exchangeRate: args.exchangeRate,
      paymentMethod: args.paymentMethod,
      reference: args.reference,
      costCenterId: args.costCenterId,
      documentStatus: "draft",
      postingStatus: "unposted",
      allocationStatus: "unallocated",
      notes: args.notes,
      createdBy: args.createdBy,
      createdAt: Date.now(),
    });

    await logAudit(ctx, {
      companyId: args.companyId,
      userId: args.createdBy,
      action: "create",
      module: "treasury",
      documentType: "cashPaymentVoucher",
      documentId: String(voucherId),
    });

    return { voucherId, voucherNumber };
  },
});

export const postCashPaymentVoucher = mutation({
  args: {
    voucherId: v.id("cashPaymentVouchers"),
    userId: v.id("users"),
    apAccountId: v.id("accounts"),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند الصرف غير موجود");
    if (voucher.postingStatus === "posted") throw new Error("السند مرحل مسبقاً");

    await validatePeriodOpen(ctx, voucher.periodId);

    const journalLines = buildCashPaymentJournal(
      {
        _id: voucher._id,
        voucherNumber: voucher.voucherNumber,
        cashAccountId: voucher.cashAccountId,
        amount: voucher.amount,
        supplierId: voucher.supplierId,
        paymentType: voucher.paymentType,
      },
      args.apAccountId
    );

    const journalEntryId = await postJournalEntry(
      ctx,
      {
        companyId: voucher.companyId,
        branchId: voucher.branchId,
        journalType: "auto_payment",
        entryDate: voucher.voucherDate,
        periodId: voucher.periodId,
        currencyId: voucher.currencyId,
        exchangeRate: voucher.exchangeRate,
        sourceType: "cashPaymentVoucher",
        sourceId: voucher._id,
        description: `سند صرف ${voucher.voucherNumber} - ${voucher.paidTo}`,
        isAutoGenerated: true,
        createdBy: args.userId,
      },
      journalLines
    );

    await ctx.db.patch(args.voucherId, {
      postingStatus: "posted",
      documentStatus: "approved",
      journalEntryId,
    });

    return { success: true, journalEntryId };
  },
});

export const allocatePayment = mutation({
  args: {
    voucherId: v.id("cashPaymentVouchers"),
    userId: v.id("users"),
    allocations: v.array(
      v.object({
        invoiceId: v.id("purchaseInvoices"),
        amount: v.number(),
      })
    ),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند الصرف غير موجود");
    if (voucher.postingStatus !== "posted") {
      throw new Error("يجب ترحيل سند الصرف أولاً");
    }

    const existingAllocations = await ctx.db
      .query("paymentAllocations")
      .withIndex("by_voucher", (q) => q.eq("voucherId", args.voucherId))
      .filter((q) => q.eq(q.field("isReversed"), false))
      .collect();

    const alreadyAllocated = existingAllocations.reduce(
      (s, a) => s + a.allocatedAmount,
      0
    );
    const newAllocationTotal = args.allocations.reduce((s, a) => s + a.amount, 0);

    if (alreadyAllocated + newAllocationTotal > voucher.amount) {
      throw new Error("المبلغ المخصص يتجاوز رصيد السند");
    }

    const today = new Date().toISOString().split("T")[0];

    for (const alloc of args.allocations) {
      const invoice = await ctx.db.get(alloc.invoiceId);
      if (!invoice) throw new Error(`الفاتورة غير موجودة`);

      await ctx.db.insert("paymentAllocations", {
        voucherId: args.voucherId,
        invoiceId: alloc.invoiceId,
        allocatedAmount: alloc.amount,
        allocationDate: today,
        createdBy: args.userId,
        createdAt: Date.now(),
        isReversed: false,
      });

      const allInvoiceAllocations = await ctx.db
        .query("paymentAllocations")
        .withIndex("by_invoice", (q) => q.eq("invoiceId", alloc.invoiceId))
        .filter((q) => q.eq(q.field("isReversed"), false))
        .collect();

      const totalAllocated =
        allInvoiceAllocations.reduce((s, a) => s + a.allocatedAmount, 0) +
        alloc.amount;

      let paymentStatus: "unpaid" | "partial" | "paid" = "unpaid";
      if (totalAllocated >= invoice.totalAmount) {
        paymentStatus = "paid";
      } else if (totalAllocated > 0) {
        paymentStatus = "partial";
      }

      await ctx.db.patch(alloc.invoiceId, { paymentStatus });
    }

    const totalAllocatedNow = alreadyAllocated + newAllocationTotal;
    let allocationStatus: "unallocated" | "partial" | "fully_allocated" =
      "unallocated";
    if (totalAllocatedNow >= voucher.amount) {
      allocationStatus = "fully_allocated";
    } else if (totalAllocatedNow > 0) {
      allocationStatus = "partial";
    }

    await ctx.db.patch(args.voucherId, { allocationStatus });

    return { success: true };
  },
});

export const cancelCashPaymentVoucher = mutation({
  args: {
    voucherId: v.id("cashPaymentVouchers"),
    userId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند الصرف غير موجود");
    if (voucher.postingStatus === "posted") {
      throw new Error("لا يمكن إلغاء سند صرف مرحل");
    }
    const user = await assertUserPermission(ctx, args.userId, "treasury", "edit");
    assertUserBranch(user, voucher.branchId);
    await ctx.db.patch(args.voucherId, { documentStatus: "cancelled" });
    return { success: true };
  },
});

export const deleteDraftCashPaymentVoucher = mutation({
  args: {
    voucherId: v.id("cashPaymentVouchers"),
    userId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند الصرف غير موجود");
    if (voucher.documentStatus !== "draft" || voucher.postingStatus !== "unposted") {
      throw new Error("يمكن حذف مسودات سندات الصرف فقط");
    }
    const user = await assertUserPermission(ctx, args.userId, "treasury", "delete");
    assertUserBranch(user, voucher.branchId);
    await ctx.db.delete(args.voucherId);
    return { success: true };
  },
});

export const reverseCashPaymentVoucher = mutation({
  args: {
    voucherId: v.id("cashPaymentVouchers"),
    userId: v.id("users"),
    reversalDate: v.string(),
    reversalPeriodId: v.id("accountingPeriods"),
  },
  handler: async (ctx, args) => {
    const voucher = await ctx.db.get(args.voucherId);
    if (!voucher) throw new Error("سند الصرف غير موجود");
    if (voucher.postingStatus !== "posted") {
      throw new Error("يمكن عكس سندات الصرف المرحلة فقط");
    }
    if (!voucher.journalEntryId) {
      throw new Error("لا يوجد قيد محاسبي مرتبط بسند الصرف");
    }

    const allocations = await ctx.db
      .query("paymentAllocations")
      .withIndex("by_voucher", (q) => q.eq("voucherId", args.voucherId))
      .filter((q) => q.eq(q.field("isReversed"), false))
      .collect();
    if (allocations.length > 0) {
      throw new Error("لا يمكن عكس سند صرف عليه تخصيصات. قم بعكس التخصيصات أولاً");
    }

    await reverseJournalEntry(ctx, voucher.journalEntryId, args.reversalDate, args.reversalPeriodId, args.userId);
    await ctx.db.patch(args.voucherId, { postingStatus: "reversed" });
    return { success: true };
  },
});

// ─── CHEQUES ──────────────────────────────────────────────────────────────────

export const createCheque = mutation({
  args: {
    companyId: v.id("companies"),
    branchId: v.id("branches"),
    chequeNumber: v.string(),
    chequeType: v.union(v.literal("received"), v.literal("issued")),
    bankAccountId: v.id("bankAccounts"),
    customerId: v.optional(v.id("customers")),
    supplierId: v.optional(v.id("suppliers")),
    amount: v.number(),
    currencyId: v.id("currencies"),
    exchangeRate: v.number(),
    issueDate: v.optional(v.string()),
    dueDate: v.string(),
    drawnOnBank: v.optional(v.string()),
    glAccountId: v.id("accounts"),
    notes: v.optional(v.string()),
    createdBy: v.id("users"),
  },
  handler: async (ctx, args) => {
    // Permission check before any DB writes
    const chequeUser = await assertUserPermission(ctx, args.createdBy, "treasury", "create");
    assertUserBranch(chequeUser, args.branchId);

    const chequeId = await ctx.db.insert("cheques", {
      ...args,
      chequeStatus: args.chequeType === "received" ? "received" : "issued",
      createdAt: Date.now(),
    });

    await logAudit(ctx, {
      companyId: args.companyId,
      userId: args.createdBy,
      action: "create",
      module: "treasury",
      documentType: "cheque",
      documentId: String(chequeId),
    });

    return { chequeId };
  },
});

export const updateChequeStatus = mutation({
  args: {
    chequeId: v.id("cheques"),
    newStatus: v.union(
      v.literal("deposited"),
      v.literal("cleared"),
      v.literal("bounced"),
      v.literal("presented"),
      v.literal("cleared_issued"),
      v.literal("stopped")
    ),
    date: v.string(),
    userId: v.id("users"),
    periodId: v.optional(v.id("accountingPeriods")),
    bankAccountId: v.optional(v.id("accounts")),
    chequesInTransitAccountId: v.optional(v.id("accounts")),
    bounceChargesAccountId: v.optional(v.id("accounts")),
    bounceReason: v.optional(v.string()),
    notes: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const cheque = await ctx.db.get(args.chequeId);
    if (!cheque) throw new Error("الشيك غير موجود");

    // Permission check before any updates
    const chequeStatusUser = await assertUserPermission(ctx, args.userId, "treasury", "edit");
    assertUserBranch(chequeStatusUser, cheque.branchId);

    const updates: Record<string, any> = {
      chequeStatus: args.newStatus,
      notes: args.notes ?? cheque.notes,
    };

    if (args.newStatus === "deposited") {
      updates.depositDate = args.date;
    }
    if (args.newStatus === "cleared" || args.newStatus === "cleared_issued") {
      updates.clearingDate = args.date;

      // Create clearing journal entry if accounts provided
      if (args.periodId && args.bankAccountId && args.chequesInTransitAccountId) {
        const journalEntryId = await postJournalEntry(
          ctx,
          {
            companyId: cheque.companyId,
            branchId: cheque.branchId,
            journalType: "auto_cheque",
            entryDate: args.date,
            periodId: args.periodId,
            currencyId: cheque.currencyId,
            exchangeRate: cheque.exchangeRate,
            sourceType: "cheque",
            sourceId: cheque._id,
            description: `تسوية شيك رقم ${cheque.chequeNumber}`,
            isAutoGenerated: true,
            createdBy: args.userId,
          },
          cheque.chequeType === "received"
            ? [
                {
                  accountId: args.bankAccountId,
                  description: `تحصيل شيك ${cheque.chequeNumber}`,
                  debit: cheque.amount,
                  credit: 0,
                },
                {
                  accountId: args.chequesInTransitAccountId,
                  description: `تحصيل شيك ${cheque.chequeNumber}`,
                  debit: 0,
                  credit: cheque.amount,
                },
              ]
            : [
                {
                  accountId: args.chequesInTransitAccountId,
                  description: `صرف شيك ${cheque.chequeNumber}`,
                  debit: cheque.amount,
                  credit: 0,
                },
                {
                  accountId: args.bankAccountId,
                  description: `صرف شيك ${cheque.chequeNumber}`,
                  debit: 0,
                  credit: cheque.amount,
                },
              ]
        );
        updates.clearingEntryId = journalEntryId;
      }
    }
    if (args.newStatus === "bounced") {
      updates.bounceDate = args.date;
      updates.bounceReason = args.bounceReason;
    }
    if (args.newStatus === "stopped") {
      // No additional journal needed
    }

    await ctx.db.patch(args.chequeId, updates);

    await logAudit(ctx, {
      companyId: cheque.companyId,
      userId: args.userId,
      action: "edit",
      module: "treasury",
      documentType: "cheque",
      documentId: String(args.chequeId),
      details: JSON.stringify({ newStatus: args.newStatus }),
    });

    return { success: true };
  },
});

// ─── BANK TRANSFERS ───────────────────────────────────────────────────────────

export const createBankTransfer = mutation({
  args: {
    companyId: v.id("companies"),
    branchId: v.id("branches"),
    transferDate: v.string(),
    periodId: v.id("accountingPeriods"),
    fromBankAccountId: v.id("bankAccounts"),
    toBankAccountId: v.id("bankAccounts"),
    amount: v.number(),
    currencyId: v.id("currencies"),
    reference: v.optional(v.string()),
    description: v.optional(v.string()),
    createdBy: v.id("users"),
  },
  handler: async (ctx, args) => {
    // Permission check before any processing
    const transferUser = await assertUserPermission(ctx, args.createdBy, "treasury", "create");
    assertUserBranch(transferUser, args.branchId);

    // 1. Validate accounts are different
    if (args.fromBankAccountId === args.toBankAccountId) {
      throw new Error("لا يمكن التحويل من وإلى نفس الحساب البنكي");
    }

    await validatePeriodOpen(ctx, args.periodId);
    await assertPeriodOpen(ctx, args.transferDate, args.companyId);

    // 2. Look up both bank accounts to get their glAccountId
    const fromBankAccount = await ctx.db.get(args.fromBankAccountId);
    if (!fromBankAccount) throw new Error("حساب البنك المُحوَّل منه غير موجود");
    if (!fromBankAccount.glAccountId) throw new Error("حساب البنك المُحوَّل منه لا يرتبط بحساب محاسبي");

    const toBankAccount = await ctx.db.get(args.toBankAccountId);
    if (!toBankAccount) throw new Error("حساب البنك المُحوَّل إليه غير موجود");
    if (!toBankAccount.glAccountId) throw new Error("حساب البنك المُحوَّل إليه لا يرتبط بحساب محاسبي");

    // 3. Generate transfer number
    const fiscalYear = await ctx.db
      .query("fiscalYears")
      .withIndex("by_company", (q) => q.eq("companyId", args.companyId))
      .filter((q) => q.eq(q.field("status"), "open"))
      .first();

    let transferNumber = `TRF-${Date.now()}`;
    if (fiscalYear) {
      transferNumber = await generateDocumentNumber(ctx, args.branchId, fiscalYear._id, "TRF");
    }

    // 4. Build journal lines:
    //    DEBIT: toBankAccount.glAccountId  (money going IN)
    //    CREDIT: fromBankAccount.glAccountId (money going OUT)
    const journalLines = [
      {
        accountId: toBankAccount.glAccountId,
        description: `تحويل بنكي ${transferNumber} - وارد`,
        debit: args.amount,
        credit: 0,
      },
      {
        accountId: fromBankAccount.glAccountId,
        description: `تحويل بنكي ${transferNumber} - صادر`,
        debit: 0,
        credit: args.amount,
      },
    ];

    // 5. Create the journal entry (posts immediately)
    const journalEntryId = await postJournalEntry(
      ctx,
      {
        companyId: args.companyId,
        branchId: args.branchId,
        journalType: "auto_transfer",
        entryDate: args.transferDate,
        periodId: args.periodId,
        currencyId: args.currencyId,
        exchangeRate: 1,
        sourceType: "bankTransfer",
        sourceId: transferNumber,
        description: args.description
          ? `تحويل بنكي ${transferNumber} - ${args.description}`
          : `تحويل بنكي ${transferNumber}`,
        isAutoGenerated: true,
        createdBy: args.createdBy,
      },
      journalLines
    );

    // 6. Insert bankTransfer record — posted immediately
    const transferId = await ctx.db.insert("bankTransfers", {
      companyId: args.companyId,
      branchId: args.branchId,
      transferNumber,
      transferDate: args.transferDate,
      periodId: args.periodId,
      fromAccountId: args.fromBankAccountId,
      toAccountId: args.toBankAccountId,
      amount: args.amount,
      feeAmount: 0,
      currencyId: args.currencyId,
      reference: args.reference,
      documentStatus: "approved",
      postingStatus: "posted",
      journalEntryId,
      notes: args.description,
      createdBy: args.createdBy,
      createdAt: Date.now(),
    });

    await logAudit(ctx, {
      companyId: args.companyId,
      userId: args.createdBy,
      action: "create",
      module: "treasury",
      documentType: "bankTransfer",
      documentId: String(transferId),
    });

    return { transferId, transferNumber };
  },
});

// ─── QUERIES ──────────────────────────────────────────────────────────────────

export const listReceipts = query({
  args: {
    companyId: v.id("companies"),
    branchId: v.optional(v.id("branches")),
    fromDate: v.optional(v.string()),
    toDate: v.optional(v.string()),
    postingStatus: v.optional(
      v.union(v.literal("unposted"), v.literal("posted"), v.literal("reversed"))
    ),
    allocationStatus: v.optional(
      v.union(v.literal("unallocated"), v.literal("partial"), v.literal("fully_allocated"))
    ),
  },
  handler: async (ctx, args) => {
    const all = await ctx.db
      .query("cashReceiptVouchers")
      .filter((q) => q.eq(q.field("companyId"), args.companyId))
      .order("desc")
      .take(200);

    const filtered = all.filter((r) => {
      if (args.branchId && r.branchId !== args.branchId) return false;
      if (args.fromDate && r.voucherDate < args.fromDate) return false;
      if (args.toDate && r.voucherDate > args.toDate) return false;
      if (args.postingStatus && r.postingStatus !== args.postingStatus) return false;
      if (args.allocationStatus && r.allocationStatus !== args.allocationStatus) return false;
      return true;
    });

    return Promise.all(
      filtered.map(async (r) => {
        const customer = r.customerId ? await ctx.db.get(r.customerId) : null;
        return { ...r, customerName: customer?.nameAr ?? null };
      })
    );
  },
});

export const listCashReceiptVouchers = query({
  args: {
    branchId: v.optional(v.id("branches")),
    fromDate: v.optional(v.string()),
    toDate: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    let vouchers = args.branchId
      ? await ctx.db
          .query("cashReceiptVouchers")
          .withIndex("by_branch", (q) => q.eq("branchId", args.branchId!))
          .collect()
      : await ctx.db.query("cashReceiptVouchers").collect();

    if (args.fromDate)
      vouchers = vouchers.filter((v) => v.voucherDate >= args.fromDate!);
    if (args.toDate)
      vouchers = vouchers.filter((v) => v.voucherDate <= args.toDate!);

    return vouchers.sort((a, b) => b.voucherDate.localeCompare(a.voucherDate));
  },
});

export const listCheques = query({
  args: {
    branchId: v.optional(v.id("branches")),
    chequeType: v.optional(v.union(v.literal("received"), v.literal("issued"))),
    fromDate: v.optional(v.string()),
    toDate: v.optional(v.string()),
    chequeStatus: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    let cheques = args.branchId
      ? await ctx.db
          .query("cheques")
          .withIndex("by_branch", (q) => q.eq("branchId", args.branchId!))
          .collect()
      : await ctx.db.query("cheques").collect();

    if (args.chequeType) cheques = cheques.filter((c) => c.chequeType === args.chequeType);
    if (args.fromDate) cheques = cheques.filter((c) => c.dueDate >= args.fromDate!);
    if (args.toDate) cheques = cheques.filter((c) => c.dueDate <= args.toDate!);
    if (args.chequeStatus) cheques = cheques.filter((c) => c.chequeStatus === args.chequeStatus);

    return cheques.sort((a, b) => a.dueDate.localeCompare(b.dueDate));
  },
});

// --- LIST CASH PAYMENTS ---
export const listCashPayments = query({
  args: {
    companyId: v.id('companies'),
    branchId: v.optional(v.id('branches')),
    fromDate: v.optional(v.string()),
    toDate: v.optional(v.string()),
    postingStatus: v.optional(v.string()),
  },
  handler: async (ctx, { companyId, branchId, fromDate, toDate, postingStatus }) => {
    let vouchers = await ctx.db
      .query('cashPaymentVouchers')
      .filter((q) => q.eq(q.field('companyId'), companyId))
      .order('desc')
      .take(300);
    if (branchId) vouchers = vouchers.filter((v) => v.branchId === branchId);
    if (fromDate) vouchers = vouchers.filter((v) => v.voucherDate >= fromDate);
    if (toDate) vouchers = vouchers.filter((v) => v.voucherDate <= toDate);
    if (postingStatus) vouchers = vouchers.filter((v) => v.postingStatus === postingStatus);
    return Promise.all(vouchers.map(async (v) => {
      const supplier = v.supplierId ? await ctx.db.get(v.supplierId) : null;
      return { ...v, supplierName: supplier ? supplier.nameAr : undefined };
    }));
  },
});

// --- LIST BANK ACCOUNTS ---
// ─── GET RECEIPT VOUCHER BY ID ────────────────────────────────────────────────

export const getReceiptById = query({
  args: { voucherId: v.id("cashReceiptVouchers") },
  handler: async (ctx, { voucherId }) => {
    const voucher = await ctx.db.get(voucherId);
    if (!voucher) return null;
    const company  = await ctx.db.get(voucher.companyId);
    const branch   = await ctx.db.get(voucher.branchId);
    const customer = voucher.customerId ? await ctx.db.get(voucher.customerId) : null;
    const account  = await ctx.db.get(voucher.cashAccountId);
    return {
      ...voucher,
      companyNameAr: company?.nameAr ?? "",
      companyNameEn: (company as any)?.nameEn ?? company?.nameAr ?? "",
      companyAddress: (company as any)?.address ?? "",
      companyVatNumber: (company as any)?.taxNumber ?? "",
      companyPhone: (company as any)?.phone ?? "",
      branchNameAr: branch?.nameAr ?? "",
      branchNameEn: (branch as any)?.nameEn ?? branch?.nameAr ?? "",
      customerNameAr: customer?.nameAr ?? "",
      customerNameEn: (customer as any)?.nameEn ?? customer?.nameAr ?? "",
      customerPhone: (customer as any)?.phone ?? "",
      accountName: account?.nameAr ?? "",
    };
  },
});

// ─── GET PAYMENT VOUCHER BY ID ────────────────────────────────────────────────

export const getPaymentById = query({
  args: { voucherId: v.id("cashPaymentVouchers") },
  handler: async (ctx, { voucherId }) => {
    const voucher = await ctx.db.get(voucherId);
    if (!voucher) return null;
    const company  = await ctx.db.get(voucher.companyId);
    const branch   = await ctx.db.get(voucher.branchId);
    const supplier = voucher.supplierId ? await ctx.db.get(voucher.supplierId) : null;
    const account  = await ctx.db.get(voucher.cashAccountId);
    return {
      ...voucher,
      companyNameAr: company?.nameAr ?? "",
      companyNameEn: (company as any)?.nameEn ?? company?.nameAr ?? "",
      companyAddress: (company as any)?.address ?? "",
      companyVatNumber: (company as any)?.taxNumber ?? "",
      companyPhone: (company as any)?.phone ?? "",
      branchNameAr: branch?.nameAr ?? "",
      branchNameEn: (branch as any)?.nameEn ?? branch?.nameAr ?? "",
      supplierNameAr: supplier?.nameAr ?? "",
      supplierNameEn: (supplier as any)?.nameEn ?? supplier?.nameAr ?? "",
      accountName: account?.nameAr ?? "",
    };
  },
});

// ─── GET CHEQUE BY ID ─────────────────────────────────────────────────────────

export const getChequeById = query({
  args: { chequeId: v.id("cheques") },
  handler: async (ctx, { chequeId }) => {
    const cheque = await ctx.db.get(chequeId);
    if (!cheque) return null;
    const company     = await ctx.db.get(cheque.companyId);
    const branch      = await ctx.db.get(cheque.branchId);
    const customer    = cheque.customerId ? await ctx.db.get(cheque.customerId) : null;
    const supplier    = cheque.supplierId ? await ctx.db.get(cheque.supplierId) : null;
    const bankAccount = await ctx.db.get(cheque.bankAccountId);
    const glAccount   = await ctx.db.get(cheque.glAccountId);
    return {
      ...cheque,
      companyNameAr: company?.nameAr ?? "",
      companyNameEn: (company as any)?.nameEn ?? company?.nameAr ?? "",
      companyAddress: (company as any)?.address ?? "",
      companyPhone: (company as any)?.phone ?? "",
      branchNameAr: branch?.nameAr ?? "",
      branchNameEn: (branch as any)?.nameEn ?? branch?.nameAr ?? "",
      customerNameAr: customer?.nameAr ?? "",
      customerNameEn: (customer as any)?.nameEn ?? customer?.nameAr ?? "",
      supplierNameAr: supplier?.nameAr ?? "",
      supplierNameEn: (supplier as any)?.nameEn ?? supplier?.nameAr ?? "",
      bankAccountName: bankAccount?.accountName ?? "",
      bankName: bankAccount?.bankName ?? "",
      glAccountName: glAccount?.nameAr ?? "",
      glAccountCode: (glAccount as any)?.code ?? "",
    };
  },
});

export const listBankAccounts = query({
  args: {
    companyId: v.id('companies'),
    includeInactive: v.optional(v.boolean()),
  },
  handler: async (ctx, { companyId, includeInactive }) => {
    const all = await ctx.db
      .query('bankAccounts')
      .withIndex('by_company', (q) => q.eq('companyId', companyId))
      .take(200);
    return includeInactive ? all : all.filter((a) => a.isActive !== false);
  },
});

export const listBankTransfers = query({
  args: {
    companyId: v.id('companies'),
    branchId: v.optional(v.id('branches')),
    fromDate: v.optional(v.string()),
    toDate: v.optional(v.string()),
  },
  handler: async (ctx, { companyId, branchId, fromDate, toDate }) => {
    let transfers = await ctx.db
      .query('bankTransfers')
      .filter((q) => q.eq(q.field('companyId'), companyId))
      .order('desc')
      .take(200);
    if (branchId) transfers = transfers.filter((t) => t.branchId === branchId);
    if (fromDate) transfers = transfers.filter((t) => t.transferDate >= fromDate);
    if (toDate) transfers = transfers.filter((t) => t.transferDate <= toDate);
    return transfers;
  },
});

export const createBankAccount = mutation({
  args: {
    companyId: v.id('companies'),
    branchId: v.optional(v.id('branches')),
    accountName: v.string(),
    bankName: v.string(),
    accountNumber: v.optional(v.string()),
    iban: v.optional(v.string()),
    currencyId: v.optional(v.id('currencies')),
    glAccountId: v.optional(v.id('accounts')),
    createdBy: v.id('users'),
  },
  handler: async (ctx, args) => {
    await assertUserPermission(ctx, args.createdBy, 'treasury', 'create');
    return await ctx.db.insert('bankAccounts', {
      companyId: args.companyId,
      branchId: args.branchId!,
      accountName: args.accountName,
      bankName: args.bankName,
      accountNumber: args.accountNumber ?? '',
      iban: args.iban ?? '',
      currencyId: args.currencyId!,
      glAccountId: args.glAccountId!,
      isActive: true,
    });
  },
});

export const deleteBankAccount = mutation({
  args: {
    bankAccountId: v.id('bankAccounts'),
    userId: v.id('users'),
  },
  handler: async (ctx, args) => {
    await assertUserPermission(ctx, args.userId, 'treasury', 'edit');
    const account = await ctx.db.get(args.bankAccountId);
    if (!account) throw new Error('الحساب البنكي غير موجود');
    // Check if used in any payment vouchers
    const linked = await ctx.db
      .query('paymentVouchers')
      .filter((q) => q.eq(q.field('bankAccountId'), args.bankAccountId))
      .first();
    if (linked) throw new Error('لا يمكن حذف الحساب لأنه مرتبط بسندات صرف');
    await ctx.db.delete(args.bankAccountId);
    return { success: true };
  },
});

export const updateBankAccount = mutation({
  args: {
    bankAccountId: v.id('bankAccounts'),
    accountName: v.optional(v.string()),
    bankName: v.optional(v.string()),
    accountNumber: v.optional(v.string()),
    iban: v.optional(v.string()),
    glAccountId: v.optional(v.id('accounts')),
    isActive: v.optional(v.boolean()),
    updatedBy: v.id('users'),
  },
  handler: async (ctx, args) => {
    await assertUserPermission(ctx, args.updatedBy, 'treasury', 'edit');
    const { bankAccountId, updatedBy, ...fields } = args;
    const patch: any = {};
    if (fields.accountName !== undefined) patch.accountName = fields.accountName;
    if (fields.bankName !== undefined) patch.bankName = fields.bankName;
    if (fields.accountNumber !== undefined) patch.accountNumber = fields.accountNumber;
    if (fields.iban !== undefined) patch.iban = fields.iban;
    if (fields.glAccountId !== undefined) patch.glAccountId = fields.glAccountId;
    if (fields.isActive !== undefined) patch.isActive = fields.isActive;
    await ctx.db.patch(bankAccountId, patch);
    return { success: true };
  },
});
