import { MutationCtx, QueryCtx } from "../_generated/server";

import { Id } from "../_generated/dataModel";



// ─── TYPES ────────────────────────────────────────────────────────────────────



export interface JournalLineInput {

  accountId: Id<"accounts">;

  subAccountType?: string;

  subAccountId?: string;

  description?: string;

  costCenterId?: Id<"costCenters">;

  documentRef?: string;

  debit: number; // * 100

  credit: number; // * 100

  foreignDebit?: number;

  foreignCredit?: number;

}



export interface JournalEntryInput {

  companyId: Id<"companies">;

  branchId: Id<"branches">;

  journalType:

    | "general"

    | "cash"

    | "expenses"

    | "adjustments"

    | "closing"

    | "reversing"

    | "opening"

    | "auto_sales"

    | "auto_purchase"

    | "auto_inventory"

    | "auto_receipt"

    | "auto_payment"

    | "auto_cheque"

    | "auto_transfer"

    | "auto_depreciation";

  entryDate: string;

  periodId: Id<"accountingPeriods">;

  currencyId: Id<"currencies">;

  exchangeRate: number;

  costCenterId?: Id<"costCenters">;

  sourceType?: string;

  sourceId?: string;

  description: string;

  isAutoGenerated: boolean;

  notes?: string;

  createdBy: Id<"users">;

}



// ─── PERIOD VALIDATION ────────────────────────────────────────────────────────



/**

 * Validates that the given accounting period is open (status = "open").

 * Throws a ConvexError if the period is closed, soft_closed, or locked.

 */

export async function validatePeriodOpen(

  ctx: QueryCtx | MutationCtx,

  periodId: Id<"accountingPeriods">

): Promise<void> {

  const period = await ctx.db.get(periodId);

  if (!period) {

    throw new Error("الفترة المحاسبية غير موجودة");

  }

  if (period.status === "locked") {

    throw new Error(`الفترة المحاسبية "${period.name}" مقفلة ولا يمكن الترحيل إليها`);

  }

  if (period.status === "closed") {

    throw new Error(`الفترة المحاسبية "${period.name}" مغلقة ولا يمكن الترحيل إليها`);

  }

  if (period.status === "soft_closed") {

    throw new Error(`الفترة المحاسبية "${period.name}" مغلقة مؤقتاً. تواصل مع المدير للسماح بالترحيل`);

  }

}



// ─── JOURNAL BALANCE VALIDATION ──────────────────────────────────────────────



/**

 * Validates that the sum of debits equals the sum of credits in a journal entry.

 * Throws if they do not match (within 1 unit tolerance for rounding).

 */

export function validateJournalBalance(lines: JournalLineInput[]): void {

  let totalDebit = 0;

  let totalCredit = 0;

  for (const line of lines) {

    totalDebit += line.debit;

    totalCredit += line.credit;

  }

  const difference = Math.abs(totalDebit - totalCredit);

  if (difference > 1) {

    const debitDisplay = (totalDebit / 100).toFixed(2);

    const creditDisplay = (totalCredit / 100).toFixed(2);

    throw new Error(

      `القيد غير متوازن: المدين ${debitDisplay} ≠ الدائن ${creditDisplay}`

    );

  }

}



// ─── DOCUMENT SEQUENCE GENERATION ────────────────────────────────────────────



/**

 * Atomically increments the document sequence and returns the formatted document number.

 * e.g. prefix="SI", currentNumber=5, padding=4 → "SI-0006-2026"

 */

export async function generateDocumentNumber(

  ctx: MutationCtx,

  branchId: Id<"branches">,

  fiscalYearId: Id<"fiscalYears">,

  documentType: string

): Promise<string> {

  const existing = await ctx.db

    .query("documentSequences")

    .withIndex("by_branch_year_type", (q) =>

      q.eq("branchId", branchId).eq("fiscalYearId", fiscalYearId).eq("documentType", documentType)

    )

    .unique();



  if (!existing) {

    // Auto-create sequence if not found

    const fiscalYear = await ctx.db.get(fiscalYearId);

    const yearCode = fiscalYear ? fiscalYear.code : new Date().getFullYear().toString();

    const newSeqId = await ctx.db.insert("documentSequences", {

      branchId,

      fiscalYearId,

      documentType,

      prefix: documentType,

      currentNumber: 1,

      padding: 4,

      resetYearly: true,

    });

    const seq = await ctx.db.get(newSeqId);

    const num = String(1).padStart(seq!.padding, "0");

    return `${seq!.prefix}-${num}-${yearCode}`;

  }



  const nextNumber = existing.currentNumber + 1;

  await ctx.db.patch(existing._id, { currentNumber: nextNumber });



  const fiscalYear = await ctx.db.get(fiscalYearId);

  const yearCode = fiscalYear ? fiscalYear.code : new Date().getFullYear().toString();

  const num = String(nextNumber).padStart(existing.padding, "0");

  return `${existing.prefix}-${num}-${yearCode}`;

}



// ─── POST JOURNAL ENTRY ───────────────────────────────────────────────────────



/**

 * Creates a journal entry with its lines atomically.

 * Validates:

 *  1. Period is open

 *  2. Lines are balanced (debit = credit)

 *  3. All accounts are postable and active

 * Returns the journal entry Id.

 */

export async function postJournalEntry(

  ctx: MutationCtx,

  entryData: JournalEntryInput,

  lines: JournalLineInput[]

): Promise<Id<"journalEntries">> {

  // 1. Validate period

  await validatePeriodOpen(ctx, entryData.periodId);



  // 2. Validate balance

  validateJournalBalance(lines);



  // 3. Validate all accounts are postable

  for (const line of lines) {

    const account = await ctx.db.get(line.accountId);

    if (!account) {

      throw new Error(`الحساب غير موجود: ${line.accountId}`);

    }

    if (!account.isPostable) {

      throw new Error(`الحساب "${account.nameAr}" (${account.code}) غير قابل للترحيل — استخدم حساباً فرعياً`);

    }

    if (!account.isActive) {

      throw new Error(`الحساب "${account.nameAr}" (${account.code}) غير نشط`);

    }

  }



  // 4. Generate entry number

  const fiscalYear = await ctx.db

    .query("fiscalYears")

    .withIndex("by_company", (q) => q.eq("companyId", entryData.companyId))

    .filter((q) => q.eq(q.field("status"), "open"))

    .first();



  let entryNumber = `JE-${Date.now()}`;

  if (fiscalYear) {

    entryNumber = await generateDocumentNumber(ctx, entryData.branchId, fiscalYear._id, "JE");

  }



  // 5. Calculate totals

  let totalDebit = 0;

  let totalCredit = 0;

  for (const line of lines) {

    totalDebit += line.debit;

    totalCredit += line.credit;

  }



  // 6. Insert journal entry

  const entryId = await ctx.db.insert("journalEntries", {

    companyId: entryData.companyId,

    branchId: entryData.branchId,

    entryNumber,

    journalType: entryData.journalType,

    entryDate: entryData.entryDate,

    periodId: entryData.periodId,

    currencyId: entryData.currencyId,

    exchangeRate: entryData.exchangeRate,

    costCenterId: entryData.costCenterId,

    sourceType: entryData.sourceType,

    sourceId: entryData.sourceId,

    description: entryData.description,

    totalDebit,

    totalCredit,

    postingStatus: "posted",

    isAutoGenerated: entryData.isAutoGenerated,

    isReversingEntry: false,

    postedBy: entryData.createdBy,

    postedAt: Date.now(),

    notes: entryData.notes,

    createdBy: entryData.createdBy,

    createdAt: Date.now(),

  });



  // 7. Insert journal lines

  for (let i = 0; i < lines.length; i++) {

    const line = lines[i];

    await ctx.db.insert("journalLines", {

      entryId,

      lineNumber: i + 1,

      accountId: line.accountId,

      subAccountType: line.subAccountType,

      subAccountId: line.subAccountId,

      description: line.description,

      costCenterId: line.costCenterId,

      documentRef: line.documentRef,

      debit: line.debit,

      credit: line.credit,

      foreignDebit: line.foreignDebit ?? 0,

      foreignCredit: line.foreignCredit ?? 0,

    });

  }



  return entryId;

}



// ─── REVERSE JOURNAL ENTRY ───────────────────────────────────────────────────



/**

 * Creates a reversing entry for an existing posted journal entry.

 * All debits and credits are swapped.

 * Marks both the original entry as "reversed" and the new entry as a reversing entry.

 */

export async function reverseJournalEntry(

  ctx: MutationCtx,

  originalEntryId: Id<"journalEntries">,

  reversalDate: string,

  reversalPeriodId: Id<"accountingPeriods">,

  userId: Id<"users">

): Promise<Id<"journalEntries">> {

  const original = await ctx.db.get(originalEntryId);

  if (!original) {

    throw new Error("القيد الأصلي غير موجود");

  }

  if (original.postingStatus !== "posted") {

    throw new Error("يمكن عكس القيود المرحلة فقط");

  }

  if (original.reversalEntryId) {

    throw new Error("هذا القيد تم عكسه مسبقاً");

  }



  await validatePeriodOpen(ctx, reversalPeriodId);



  // Get original lines

  const originalLines = await ctx.db

    .query("journalLines")

    .withIndex("by_entry", (q) => q.eq("entryId", originalEntryId))

    .collect();



  // Build reversed lines

  const reversedLines: JournalLineInput[] = originalLines.map((line) => ({

    accountId: line.accountId,

    subAccountType: line.subAccountType,

    subAccountId: line.subAccountId,

    description: line.description,

    costCenterId: line.costCenterId ?? undefined,

    documentRef: line.documentRef,

    debit: line.credit, // SWAP

    credit: line.debit, // SWAP

    foreignDebit: line.foreignCredit,

    foreignCredit: line.foreignDebit,

  }));



  // Generate reversing entry number

  const fiscalYear = await ctx.db

    .query("fiscalYears")

    .withIndex("by_company", (q) => q.eq("companyId", original.companyId))

    .filter((q) => q.eq(q.field("status"), "open"))

    .first();



  let reversalNumber = `REV-${Date.now()}`;

  if (fiscalYear) {

    reversalNumber = await generateDocumentNumber(ctx, original.branchId, fiscalYear._id, "REV");

  }



  let totalDebit = 0;

  let totalCredit = 0;

  for (const line of reversedLines) {

    totalDebit += line.debit;

    totalCredit += line.credit;

  }



  const reversalId = await ctx.db.insert("journalEntries", {

    companyId: original.companyId,

    branchId: original.branchId,

    entryNumber: reversalNumber,

    journalType: "reversing",

    entryDate: reversalDate,

    periodId: reversalPeriodId,

    currencyId: original.currencyId,

    exchangeRate: original.exchangeRate,

    costCenterId: original.costCenterId ?? undefined,

    sourceType: original.sourceType,

    sourceId: original.sourceId,

    description: `عكس: ${original.description}`,

    totalDebit,

    totalCredit,

    postingStatus: "posted",

    isAutoGenerated: true,

    isReversingEntry: true,

    reversedEntryId: originalEntryId,

    postedBy: userId,

    postedAt: Date.now(),

    notes: `قيد عكسي للقيد رقم: ${original.entryNumber}`,

    createdBy: userId,

    createdAt: Date.now(),

  });



  // Insert reversing lines

  for (let i = 0; i < reversedLines.length; i++) {

    const line = reversedLines[i];

    await ctx.db.insert("journalLines", {

      entryId: reversalId,

      lineNumber: i + 1,

      accountId: line.accountId,

      subAccountType: line.subAccountType,

      subAccountId: line.subAccountId,

      description: line.description,

      costCenterId: line.costCenterId,

      documentRef: line.documentRef,

      debit: line.debit,

      credit: line.credit,

      foreignDebit: line.foreignDebit ?? 0,

      foreignCredit: line.foreignCredit ?? 0,

    });

  }



  // Mark original as reversed

  await ctx.db.patch(originalEntryId, {

    postingStatus: "reversed",

    reversalEntryId: reversalId,

  });



  return reversalId;

}



// ─── STOCK BALANCE UPDATE ─────────────────────────────────────────────────────



/**

 * Atomically updates the stock_balance table using weighted average costing.

 * For inbound movements (purchases, returns): recalculates weighted average cost.

 * For outbound movements (sales, issues): deducts quantity at current average cost.

 * Returns { qtyBefore, qtyAfter, avgCostBefore, avgCostAfter }

 */

export async function updateStockBalance(

  ctx: MutationCtx,

  itemId: Id<"items">,

  warehouseId: Id<"warehouses">,

  quantityChange: number, // positive = in, negative = out

  unitCost: number, // * 100, used for inbound movements

  movementType: string

): Promise<{

  qtyBefore: number;

  qtyAfter: number;

  avgCostBefore: number;

  avgCostAfter: number;

}> {

  const existing = await ctx.db

    .query("stockBalance")

    .withIndex("by_item_warehouse", (q) =>

      q.eq("itemId", itemId).eq("warehouseId", warehouseId)

    )

    .unique();



  const qtyBefore = existing?.quantity ?? 0;

  const avgCostBefore = existing?.avgCost ?? 0;

  const totalValueBefore = existing?.totalValue ?? 0;



  const isInbound = quantityChange > 0;

  let newAvgCost: number;

  let newQty: number;

  let newTotalValue: number;



  if (isInbound) {

    // Weighted Average: (oldQty * oldAvg + newQty * newCost) / (oldQty + newQty)

    newQty = qtyBefore + quantityChange;

    const inboundValue = quantityChange * unitCost;

    newTotalValue = totalValueBefore + inboundValue;

    newAvgCost = newQty > 0 ? Math.round(newTotalValue / newQty) : unitCost;

  } else {

    // Outbound: deduct at current average cost

    newQty = qtyBefore + quantityChange; // quantityChange is negative

    newAvgCost = avgCostBefore; // average cost does not change on outbound

    newTotalValue = newQty > 0 ? Math.round(newQty * newAvgCost) : 0;



    // Check negative stock

    const item = await ctx.db.get(itemId);

    if (newQty < 0 && item && !item.allowNegativeStock) {

      throw new Error(

        `الكمية المتاحة غير كافية للصنف "${item.nameAr}". المتاح: ${qtyBefore}, المطلوب: ${Math.abs(quantityChange)}`

      );

    }

  }



  if (existing) {

    await ctx.db.patch(existing._id, {

      quantity: newQty,

      avgCost: newAvgCost,

      totalValue: newTotalValue,

      lastUpdated: Date.now(),

    });

  } else {

    await ctx.db.insert("stockBalance", {

      itemId,

      warehouseId,

      quantity: newQty,

      avgCost: newAvgCost,

      totalValue: newTotalValue,

      lastUpdated: Date.now(),

    });

  }



  return {

    qtyBefore,

    qtyAfter: newQty,

    avgCostBefore,

    avgCostAfter: newAvgCost,

  };

}



// ─── SALES INVOICE JOURNAL BUILDER ───────────────────────────────────────────



export interface SalesInvoiceForJournal {

  _id: Id<"salesInvoices">;

  companyId: Id<"companies">;

  branchId: Id<"branches">;

  invoiceNumber: string;

  invoiceType: string;

  customerId?: Id<"customers">;

  invoiceDate: string;

  periodId: Id<"accountingPeriods">;

  currencyId: Id<"currencies">;

  exchangeRate: number;

  costCenterId?: Id<"costCenters">;

  subtotal: number;

  discountAmount: number;

  taxableAmount: number;

  vatAmount: number;

  serviceCharge: number;

  totalAmount: number;

  cashReceived: number;

  cardReceived: number;

  creditAmount: number;

}



export interface SalesInvoiceLineForJournal {

  itemId: Id<"items">;

  lineTotal: number;

  vatAmount: number;

  unitCost: number;

  costTotal: number;

  revenueAccountId?: Id<"accounts">;

  cogsAccountId?: Id<"accounts">;

  costCenterId?: Id<"costCenters">;

}



/**

 * Builds the journal lines for posting a sales invoice.

 * Accounting rules:

 *   DR Cash/Card/AR      (for each payment method)

 *   CR Revenue accounts  (per line)

 *   CR VAT Payable       (if vatAmount > 0)

 *   DR COGS              (per line)

 *   CR Inventory         (per line)

 */

export function buildSalesInvoiceJournal(

  invoice: SalesInvoiceForJournal,

  lines: SalesInvoiceLineForJournal[],

  cashAccountId: Id<"accounts">,

  cardAccountId: Id<"accounts">,

  arAccountId: Id<"accounts">,

  vatPayableAccountId: Id<"accounts">

): JournalLineInput[] {

  const journalLines: JournalLineInput[] = [];



  // DR Cash received

  if (invoice.cashReceived > 0) {

    journalLines.push({

      accountId: cashAccountId,

      description: `نقد - ${invoice.invoiceNumber}`,

      debit: invoice.cashReceived,

      credit: 0,

      costCenterId: invoice.costCenterId,

    });

  }



  // DR Card received

  if (invoice.cardReceived > 0) {

    journalLines.push({

      accountId: cardAccountId,

      description: `بطاقة - ${invoice.invoiceNumber}`,

      debit: invoice.cardReceived,

      credit: 0,

      costCenterId: invoice.costCenterId,

    });

  }



  // DR AR (credit amount)

  if (invoice.creditAmount > 0 && invoice.customerId) {

    journalLines.push({

      accountId: arAccountId,

      subAccountType: "customer",

      subAccountId: invoice.customerId,

      description: `ذمم عميل - ${invoice.invoiceNumber}`,

      debit: invoice.creditAmount,

      credit: 0,

      costCenterId: invoice.costCenterId,

    });

  }



  // CR Revenue per line

  for (const line of lines) {

    if (line.revenueAccountId && line.lineTotal > 0) {

      journalLines.push({

        accountId: line.revenueAccountId,

        description: `إيراد - ${invoice.invoiceNumber}`,

        debit: 0,

        credit: line.lineTotal - line.vatAmount,

        costCenterId: line.costCenterId ?? invoice.costCenterId,

      });

    }

  }



  // CR VAT Payable

  if (invoice.vatAmount > 0) {

    journalLines.push({

      accountId: vatPayableAccountId,

      description: `ضريبة قيمة مضافة - ${invoice.invoiceNumber}`,

      debit: 0,

      credit: invoice.vatAmount,

    });

  }



  // DR COGS / CR Inventory per line (for stock items)

  for (const line of lines) {

    if (line.cogsAccountId && line.costTotal > 0) {

      journalLines.push({

        accountId: line.cogsAccountId,

        description: `تكلفة البضاعة المباعة - ${invoice.invoiceNumber}`,

        debit: line.costTotal,

        credit: 0,

        costCenterId: line.costCenterId ?? invoice.costCenterId,

      });

    }

  }



  return journalLines;

}



// ─── PURCHASE INVOICE JOURNAL BUILDER ────────────────────────────────────────



export interface PurchaseInvoiceForJournal {

  _id: Id<"purchaseInvoices">;

  companyId: Id<"companies">;

  branchId: Id<"branches">;

  invoiceNumber: string;

  supplierId: Id<"suppliers">;

  invoiceDate: string;

  periodId: Id<"accountingPeriods">;

  currencyId: Id<"currencies">;

  exchangeRate: number;

  subtotal: number;

  vatAmount: number;

  totalAmount: number;

}



export interface PurchaseInvoiceLineForJournal {

  lineType: string;

  lineTotal: number;

  vatAmount: number;

  accountId?: Id<"accounts">;

  costCenterId?: Id<"costCenters">;

}



/**

 * Builds the journal lines for posting a purchase invoice.

 * Accounting rules:

 *   DR Inventory / Expense accounts  (per line)

 *   DR VAT Receivable                (if VAT > 0)

 *   CR Accounts Payable              (supplier)

 */

export function buildPurchaseInvoiceJournal(

  invoice: PurchaseInvoiceForJournal,

  lines: PurchaseInvoiceLineForJournal[],

  apAccountId: Id<"accounts">,

  vatReceivableAccountId: Id<"accounts">

): JournalLineInput[] {

  const journalLines: JournalLineInput[] = [];



  // DR each line account

  for (const line of lines) {

    if (line.accountId) {

      journalLines.push({

        accountId: line.accountId,

        description: `مشتريات - ${invoice.invoiceNumber}`,

        debit: line.lineTotal - line.vatAmount,

        credit: 0,

        costCenterId: line.costCenterId,

      });

    }

  }



  // DR VAT Receivable

  if (invoice.vatAmount > 0) {

    journalLines.push({

      accountId: vatReceivableAccountId,

      description: `ضريبة مدخلات - ${invoice.invoiceNumber}`,

      debit: invoice.vatAmount,

      credit: 0,

    });

  }



  // CR Accounts Payable

  journalLines.push({

    accountId: apAccountId,

    subAccountType: "supplier",

    subAccountId: invoice.supplierId,

    description: `ذمم مورد - ${invoice.invoiceNumber}`,

    debit: 0,

    credit: invoice.totalAmount,

  });



  return journalLines;

}



// ─── CASH RECEIPT JOURNAL BUILDER ────────────────────────────────────────────



export interface CashReceiptVoucherForJournal {

  _id: Id<"cashReceiptVouchers">;

  voucherNumber: string;

  cashAccountId: Id<"accounts">;

  amount: number;

  customerId?: Id<"customers">;

  receiptType: string;

}



/**

 * Builds journal lines for a cash receipt voucher.

 * DR Cash/Bank

 * CR AR (if customer payment) or CR Other Income account

 */

export function buildCashReceiptJournal(

  voucher: CashReceiptVoucherForJournal,

  arAccountId: Id<"accounts">

): JournalLineInput[] {

  return [

    {

      accountId: voucher.cashAccountId,

      description: `Cash Receipt / سند قبض - ${voucher.voucherNumber}`,

      debit: voucher.amount,

      credit: 0,

    },

    {

      accountId: arAccountId,

      subAccountType: voucher.receiptType === "customer_payment" ? "customer" : undefined,

      subAccountId: voucher.customerId ? String(voucher.customerId) : undefined,

      description: `Cash Receipt / سند قبض - ${voucher.voucherNumber}`,

      debit: 0,

      credit: voucher.amount,

    },

  ];

}



// ─── CASH PAYMENT JOURNAL BUILDER ────────────────────────────────────────────



export interface CashPaymentVoucherForJournal {

  _id: Id<"cashPaymentVouchers">;

  voucherNumber: string;

  cashAccountId: Id<"accounts">;

  amount: number;

  supplierId?: Id<"suppliers">;

  paymentType: string;

}



/**

 * Builds journal lines for a cash payment voucher.

 * DR AP (if supplier payment) or DR Expense account

 * CR Cash/Bank

 */

export function buildCashPaymentJournal(

  voucher: CashPaymentVoucherForJournal,

  apAccountId: Id<"accounts">

): JournalLineInput[] {

  return [

    {

      accountId: apAccountId,

      subAccountType: voucher.paymentType === "supplier_payment" ? "supplier" : undefined,

      subAccountId: voucher.supplierId ? String(voucher.supplierId) : undefined,

      description: `Cash Payment / سند صرف - ${voucher.voucherNumber}`,

      debit: voucher.amount,

      credit: 0,

    },

    {

      accountId: voucher.cashAccountId,

      description: `Cash Payment / سند صرف - ${voucher.voucherNumber}`,

      debit: 0,

      credit: voucher.amount,

    },

  ];

}



